// Code generated by VDL v0.5.0-alpha.5 (commit 1aaf1f7) using varavelio/vdl-plugin-rpc-go@v0.1.2 (hash da31800b)
// Any changes will be overwritten the next time VDL is run. DO NOT EDIT.
// Learn more: https://github.com/varavelio/vdl

package vdl

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	json "github.com/goccy/go-json"
	"io"
	"math/rand"
	"net/http"
	"strings"
	"sync"
	"time"
)

// -----------------------------------------------------------------------------
// RPC Catalog
// -----------------------------------------------------------------------------

// VDLPaths contains the generated path catalog for every procedure and stream.
var VDLPaths = struct {
	Database struct {
		Query string
	}
	System struct {
		Health  string
		Session string
		Status  string
	}
}{
	Database: struct {
		Query string
	}{
		Query: "/Database/query",
	},
	System: struct {
		Health  string
		Session string
		Status  string
	}{
		Health:  "/System/health",
		Session: "/System/session",
		Status:  "/System/status",
	},
}

// VDLProcedures contains every generated procedure definition.
var VDLProcedures = []OperationDefinition{
	{
		RPCName:     "Database",
		Name:        "query",
		Type:        OperationTypeProc,
		Annotations: []Annotation{},
	},
	{
		RPCName:     "System",
		Name:        "health",
		Type:        OperationTypeProc,
		Annotations: []Annotation{},
	},
	{
		RPCName:     "System",
		Name:        "session",
		Type:        OperationTypeProc,
		Annotations: []Annotation{},
	},
	{
		RPCName:     "System",
		Name:        "status",
		Type:        OperationTypeProc,
		Annotations: []Annotation{},
	},
}

// VDLStreams contains every generated stream definition.
var VDLStreams = []OperationDefinition{}

// -----------------------------------------------------------------------------
// RPC Core Types
// -----------------------------------------------------------------------------

// OperationType identifies the transport behavior of an RPC operation and can
// be proc or stream.
type OperationType string

const (
	// OperationTypeProc identifies a request-response procedure.
	OperationTypeProc OperationType = "proc"
	// OperationTypeStream identifies a Server-Sent Events stream.
	OperationTypeStream OperationType = "stream"
)

// Annotation represents operation-level annotation metadata preserved from VDL.
type Annotation struct {
	// Name is the annotation identifier without the @ prefix.
	Name string
	// Argument contains the resolved annotation payload when one was declared.
	Argument any
}

// OperationDefinition describes a generated procedure or stream.
type OperationDefinition struct {
	// RPCName is the VDL service name that owns the operation.
	RPCName string
	// Name is the VDL field name of the operation.
	Name string
	// Type indicates whether the operation is a procedure or a stream.
	Type OperationType
	// Annotations contains every non-marker annotation declared on the operation.
	Annotations []Annotation
}

// Path returns the transport path used by the generated client and server.
func (o OperationDefinition) Path() string {
	return "/" + o.RPCName + "/" + o.Name
}

// cloneAnnotations returns a shallow copy of the given annotations slice.
func cloneAnnotations(annotations []Annotation) []Annotation {
	if len(annotations) == 0 {
		return nil
	}
	clone := make([]Annotation, len(annotations))
	copy(clone, annotations)
	return clone
}

// Void represents the absence of an input or output payload.
type Void struct{}

// Response represents the response of a VDL call.
type Response[T any] struct {
	Ok     bool  `json:"ok"`
	Output T     `json:"output,omitempty,omitzero"`
	Error  Error `json:"error,omitzero"`
}

// Write writes the response as JSON to the provided writer.
func (r Response[T]) Write(w io.Writer) error {
	return json.NewEncoder(w).Encode(r)
}

// String returns the response as a JSON string.
func (r Response[T]) String() string {
	encoded, err := json.Marshal(r)
	if err != nil {
		return fmt.Sprintf(`{"ok":false,"error":{"message":%q}}`, "failed to marshal response: "+err.Error())
	}
	return string(encoded)
}

// Bytes returns the response as a JSON byte slice.
func (r Response[T]) Bytes() []byte {
	return []byte(r.String())
}

// Error represents a standardized error in the VDL system.
//
// It provides structured information about errors that occur within the system,
// enabling consistent error handling across servers and clients.
//
// Fields:
//   - Message: A human-readable description of the error.
//   - Category: Optional. Categorizes the error by its nature or source (e.g., "ValidationError", "DatabaseError").
//   - Code: Optional. A machine-readable identifier for the specific error condition (e.g., "INVALID_EMAIL").
//   - Details: Optional. Additional information about the error.
//
// The struct implements the error interface.
type Error struct {
	// Message provides a human-readable description of the error.
	//
	// This message can be displayed to end-users or used for logging and debugging purposes.
	//
	// Use Cases:
	//   1. Message can be directly shown to the user to inform them of the issue.
	//   2. Developers can use Message in logs to diagnose problems during development or in production.
	Message string `json:"message"`
	// Category categorizes the error by its nature or source.
	//
	// Examples:
	//   - "ValidationError" for input validation errors.
	//   - "DatabaseError" for errors originating from database operations.
	//   - "AuthenticationError" for authentication-related issues.
	//
	// Use Cases:
	//   1. In middleware, you can use Category to determine how to handle the error.
	//      For instance, you might log "InternalError" types and return a generic message to the client.
	//   2. Clients can inspect the Category to decide whether to prompt the user for action,
	//      such as re-authentication if the Category is "AuthenticationError".
	Category string `json:"category,omitzero"`
	// Code is a machine-readable identifier for the specific error condition.
	//
	// Examples:
	//   - "INVALID_EMAIL" when an email address fails validation.
	//   - "USER_NOT_FOUND" when a requested user does not exist.
	//   - "RATE_LIMIT_EXCEEDED" when a client has made too many requests.
	//
	// Use Cases:
	//   1. Clients can map Codes to localized error messages for internationalization (i18n),
	//      displaying appropriate messages based on the user's language settings.
	//   2. Clients or middleware can implement specific logic based on the Code,
	//      such as retry mechanisms for "TEMPORARY_FAILURE" or showing captcha for "RATE_LIMIT_EXCEEDED".
	Code string `json:"code,omitzero"`
	// Details contains optional additional information about the error.
	//
	// This field can include any relevant data that provides more context about the error.
	// The contents should be serializable to JSON.
	//
	// Use Cases:
	//   1. Providing field-level validation errors, e.g., Details could be:
	//      {"fields": {"email": "Email is invalid", "password": "Password is too short"}}
	//   2. Including diagnostic information such as timestamps, request IDs, or stack traces
	//      (ensure sensitive information is not exposed to clients).
	Details map[string]any `json:"details,omitempty"`
}

// Error implements the standard error interface.
func (e Error) Error() string {
	return e.Message
}

// String implements fmt.Stringer.
func (e Error) String() string {
	return e.Message
}

// Is reports whether the target error matches this error.
//
// It checks if the target is of type Error (or *Error) and compares
// their Code and Message fields.
//
// Matching Logic:
//  1. If both errors have a Code, they match if the Codes are identical.
//  2. If one or both lack a Code, they match if the Messages are identical.
//  3. Details and Category are ignored for comparison to avoid issues with non-comparable map types.
func (e Error) Is(target error) bool {
	var t Error
	switch err := target.(type) {
	case Error:
		t = err
	case *Error:
		t = *err
	default:
		return false
	}
	if e.Code != "" && t.Code != "" {
		return e.Code == t.Code
	}
	return e.Message == t.Message
}

// ToJSON returns the Error as a JSON-formatted string including all its fields.
// This is useful for logging and debugging purposes.
func (e Error) ToJSON() string {
	b, err := json.Marshal(e)
	if err != nil {
		return fmt.Sprintf(
			`{"message":%q,"details":{"message":%q}}`,
			"failed to marshal VDL Error: "+err.Error(), e.Message,
		)
	}
	return string(b)
}

// ToError converts any error into an Error.
//
// If the provided error is already a Error, it returns it as is.
// Otherwise, it wraps the error message into a new Error.
//
// This function ensures that all errors conform to the Error structure,
// facilitating consistent error handling across the system.
func ToError(err error) Error {
	switch e := err.(type) {
	case Error:
		return e
	case *Error:
		return *e
	default:
		return Error{
			Message: err.Error(),
		}
	}
}

// -----------------------------------------------------------------------------
// Client Types
// -----------------------------------------------------------------------------

// RequestInfo contains information about the RPC request currently being executed.
//
// It is passed through interceptors and retry/reconnect deciders so callers can
// inspect the targeted RPC, operation, request payload, transport mode, and the
// non-marker annotations declared on the VDL operation.
type RequestInfo struct {
	RPCName       string
	OperationName string
	Input         any
	Type          OperationType
	Annotations   []Annotation
}

// RetryDecisionContext contains the information passed to a retry decider.
//
// The generated client evaluates this context after each failed attempt so
// callers can decide whether the request should be retried.
type RetryDecisionContext struct {
	Request        RequestInfo
	Attempt        int
	ResponseStatus int
	Error          error
}

// RetryDecider determines whether a failed procedure attempt should be retried.
type RetryDecider func(ctx context.Context, info RetryDecisionContext) bool

// RetryConfig defines retry behavior for generated procedure calls.
//
// Parameters:
//   - MaxAttempts: Maximum number of retry attempts (default: 1)
//   - InitialDelay: Initial delay between retries (default: 0)
//   - MaxDelay: Maximum delay between retries (default: 0)
//   - DelayMultiplier: Cumulative multiplier applied to InitialDelay on each retry (default: 1.0)
//   - Jitter: Randomness factor used to avoid synchronized retries (default: 0.2)
//   - ShouldRetry: Optional callback that can override the default retry decision function
type RetryConfig struct {
	MaxAttempts     int
	InitialDelay    time.Duration
	MaxDelay        time.Duration
	DelayMultiplier float64
	Jitter          float64
	ShouldRetry     RetryDecider
}

// TimeoutConfig defines timeout behavior for procedure calls.
type TimeoutConfig struct {
	// Request Timeout (default: 30 seconds)
	Timeout time.Duration
}

// ReconnectDecisionContext contains the information passed to a reconnect decider.
//
// The generated client evaluates this context after a stream connection fails or
// breaks unexpectedly so callers can decide whether the stream should reconnect.
type ReconnectDecisionContext struct {
	Request        RequestInfo
	Attempt        int
	ResponseStatus int
	Error          error
}

// ReconnectDecider determines whether a failed stream connection should reconnect.
type ReconnectDecider func(ctx context.Context, info ReconnectDecisionContext) bool

// ReconnectConfig defines reconnection behavior for generated stream calls.
//
// Parameters:
//   - MaxAttempts: Maximum number of reconnection attempts (default: 30)
//   - InitialDelay: Initial delay between reconnection attempts (default: 1 second)
//   - MaxDelay: Maximum delay between reconnection attempts (default: 30 seconds)
//   - DelayMultiplier: Cumulative multiplier applied to InitialDelay on each retry (default: 1.5)
//   - Jitter: Randomness factor used to avoid synchronized reconnects (default: 0.2)
//   - ShouldReconnect: Optional callback that can override the default reconnect decision function
type ReconnectConfig struct {
	MaxAttempts     int
	InitialDelay    time.Duration
	MaxDelay        time.Duration
	DelayMultiplier float64
	Jitter          float64
	ShouldReconnect ReconnectDecider
}

// HeaderProvider receives the current headers and mutates them in place.
//
// It is called before every request, including retries and stream reconnects.
// If an error is returned, the request is aborted.
type HeaderProvider func(ctx context.Context, h http.Header) error

// Invoker is the final step in the interceptor chain that performs the actual request.
type Invoker func(ctx context.Context, req RequestInfo) (Response[json.RawMessage], error)

// Interceptor is middleware that wraps request execution.
type Interceptor func(ctx context.Context, req RequestInfo, next Invoker) (Response[json.RawMessage], error)

// -----------------------------------------------------------------------------
// Internal Client Implementation
// -----------------------------------------------------------------------------

// internalClient is the core engine used by the generated client abstraction.
//
// It is safe for concurrent use and can be reused across procedure calls and
// stream subscriptions. The zero value is not usable; use newInternalClient.
//
// The zero value is not usable – use newInternalClient to construct one.
type internalClient struct {
	// Immutable after construction.
	baseURL       string
	httpClient    *http.Client
	operationDefs map[string]map[string]OperationDefinition

	// Dynamic components
	headerProviders []HeaderProvider
	interceptors    []Interceptor

	// RPC specific header providers
	rpcHeaderProviders map[string][]HeaderProvider

	// Default Configurations
	globalRetryConf      *RetryConfig
	globalTimeoutConf    *TimeoutConfig
	globalReconnectConf  *ReconnectConfig
	globalMaxMessageSize int64

	// Per-RPC Default Configurations
	rpcRetryConf      map[string]*RetryConfig
	rpcTimeoutConf    map[string]*TimeoutConfig
	rpcReconnectConf  map[string]*ReconnectConfig
	rpcMaxMessageSize map[string]int64

	// mu protects concurrent access to the configuration maps
	mu sync.RWMutex
}

// internalClientOption configures an internal client during construction.
type internalClientOption func(*internalClient)

// withHTTPClient supplies a custom HTTP client implementation.
func withHTTPClient(client *http.Client) internalClientOption {
	return func(value *internalClient) {
		if client != nil {
			value.httpClient = client
		}
	}
}

// withGlobalHeader registers a static header for every request.
func withGlobalHeader(key string, value string) internalClientOption {
	return func(client *internalClient) {
		client.headerProviders = append(client.headerProviders, func(_ context.Context, h http.Header) error {
			h.Set(key, value)
			return nil
		})
	}
}

// withHeaderProvider registers a dynamic header provider.
func withHeaderProvider(provider HeaderProvider) internalClientOption {
	return func(client *internalClient) {
		client.headerProviders = append(client.headerProviders, provider)
	}
}

// withInterceptor adds a transport interceptor.
func withInterceptor(interceptor Interceptor) internalClientOption {
	return func(client *internalClient) {
		client.interceptors = append(client.interceptors, interceptor)
	}
}

// withGlobalRetryConfig sets the global default retry configuration.
func withGlobalRetryConfig(conf RetryConfig) internalClientOption {
	return func(client *internalClient) {
		client.globalRetryConf = &conf
	}
}

// withGlobalTimeoutConfig sets the global default timeout configuration.
func withGlobalTimeoutConfig(conf TimeoutConfig) internalClientOption {
	return func(client *internalClient) {
		client.globalTimeoutConf = &conf
	}
}

// withGlobalReconnectConfig sets the global default reconnection configuration.
func withGlobalReconnectConfig(conf ReconnectConfig) internalClientOption {
	return func(client *internalClient) {
		client.globalReconnectConf = &conf
	}
}

// withGlobalMaxMessageSize sets the global maximum message size for streams.
func withGlobalMaxMessageSize(size int64) internalClientOption {
	return func(client *internalClient) {
		client.globalMaxMessageSize = size
	}
}

// newInternalClient creates a new internalClient capable of talking to the VDL server.
//
// The caller can optionally pass functional options to customize transport
// behavior, headers, interceptors, and retry/reconnect policies.
func newInternalClient(baseURL string, procDefs []OperationDefinition, streamDefs []OperationDefinition, opts ...internalClientOption) *internalClient {
	operationDefs := make(map[string]map[string]OperationDefinition)

	ensureRPC := func(rpcName string) {
		if _, ok := operationDefs[rpcName]; !ok {
			operationDefs[rpcName] = make(map[string]OperationDefinition)
		}
	}

	for _, def := range procDefs {
		ensureRPC(def.RPCName)
		operationDefs[def.RPCName][def.Name] = def
	}

	for _, def := range streamDefs {
		ensureRPC(def.RPCName)
		operationDefs[def.RPCName][def.Name] = def
	}

	client := &internalClient{
		baseURL:            strings.TrimRight(baseURL, "/"),
		httpClient:         http.DefaultClient,
		operationDefs:      operationDefs,
		headerProviders:    []HeaderProvider{},
		interceptors:       []Interceptor{},
		rpcHeaderProviders: make(map[string][]HeaderProvider),
		rpcRetryConf:       make(map[string]*RetryConfig),
		rpcTimeoutConf:     make(map[string]*TimeoutConfig),
		rpcReconnectConf:   make(map[string]*ReconnectConfig),
		rpcMaxMessageSize:  make(map[string]int64),
	}

	// Apply functional options.
	for _, opt := range opts {
		opt(client)
	}

	return client
}

// setRPCRetryConfig sets the default retry configuration for a specific RPC service.
func (c *internalClient) setRPCRetryConfig(rpcName string, conf RetryConfig) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.rpcRetryConf[rpcName] = &conf
}

// setRPCTimeoutConfig sets the default timeout configuration for a specific RPC service.
func (c *internalClient) setRPCTimeoutConfig(rpcName string, conf TimeoutConfig) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.rpcTimeoutConf[rpcName] = &conf
}

// setRPCReconnectConfig sets the default reconnect configuration for a specific RPC service.
func (c *internalClient) setRPCReconnectConfig(rpcName string, conf ReconnectConfig) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.rpcReconnectConf[rpcName] = &conf
}

// setRPCMaxMessageSize sets the default maximum stream message size for a specific RPC service.
func (c *internalClient) setRPCMaxMessageSize(rpcName string, size int64) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.rpcMaxMessageSize[rpcName] = size
}

// setRPCHeaderProvider adds a header provider for a specific RPC service.
func (c *internalClient) setRPCHeaderProvider(rpcName string, provider HeaderProvider) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.rpcHeaderProviders[rpcName] = append(c.rpcHeaderProviders[rpcName], provider)
}

// mergeRetryConfig resolves retry configuration using this precedence:
// operation override > RPC override > global override > default.
func (c *internalClient) mergeRetryConfig(rpcName string, opConf *RetryConfig) *RetryConfig {
	if opConf != nil {
		return opConf
	}
	c.mu.RLock()
	defer c.mu.RUnlock()
	if rpcConf, ok := c.rpcRetryConf[rpcName]; ok {
		return rpcConf
	}
	if c.globalRetryConf != nil {
		return c.globalRetryConf
	}
	return &RetryConfig{
		MaxAttempts:     1,
		InitialDelay:    0,
		MaxDelay:        0,
		DelayMultiplier: 1.0,
		Jitter:          0.2,
	}
}

// mergeTimeoutConfig resolves timeout configuration using this precedence:
// operation override > RPC override > global override > default.
func (c *internalClient) mergeTimeoutConfig(rpcName string, opConf *TimeoutConfig) *TimeoutConfig {
	if opConf != nil {
		return opConf
	}
	c.mu.RLock()
	defer c.mu.RUnlock()

	if rpcConf, ok := c.rpcTimeoutConf[rpcName]; ok {
		return rpcConf
	}
	if c.globalTimeoutConf != nil {
		return c.globalTimeoutConf
	}
	return &TimeoutConfig{Timeout: 30 * time.Second}
}

// mergeReconnectConfig resolves reconnect configuration using this precedence:
// operation override > RPC override > global override > default.
func (c *internalClient) mergeReconnectConfig(rpcName string, opConf *ReconnectConfig) *ReconnectConfig {
	if opConf != nil {
		return opConf
	}
	c.mu.RLock()
	defer c.mu.RUnlock()
	if rpcConf, ok := c.rpcReconnectConf[rpcName]; ok {
		return rpcConf
	}
	if c.globalReconnectConf != nil {
		return c.globalReconnectConf
	}
	return &ReconnectConfig{
		MaxAttempts:     30,
		InitialDelay:    time.Second,
		MaxDelay:        30 * time.Second,
		DelayMultiplier: 1.5,
		Jitter:          0.2,
	}
}

// mergeMaxMessageSize resolves the maximum stream message size using this precedence:
// operation override > RPC override > global override > default.
func (c *internalClient) mergeMaxMessageSize(rpcName string, opSize int64) int64 {
	if opSize > 0 {
		return opSize
	}
	c.mu.RLock()
	defer c.mu.RUnlock()
	if rpcSize, ok := c.rpcMaxMessageSize[rpcName]; ok && rpcSize > 0 {
		return rpcSize
	}
	if c.globalMaxMessageSize > 0 {
		return c.globalMaxMessageSize
	}
	return 4 * 1024 * 1024
}

// executeChain builds the interceptor chain and executes the final invoker.
func (c *internalClient) executeChain(ctx context.Context, req RequestInfo, final Invoker) (Response[json.RawMessage], error) {
	chain := final
	for index := len(c.interceptors) - 1; index >= 0; index-- {
		middleware := c.interceptors[index]
		next := chain
		chain = func(callCtx context.Context, callReq RequestInfo) (Response[json.RawMessage], error) {
			return middleware(callCtx, callReq, next)
		}
	}
	return chain(ctx, req)
}

// lookupOperation returns the generated operation definition for the requested RPC member.
func (c *internalClient) lookupOperation(rpcName string, operationName string) (OperationDefinition, bool) {
	if operations, ok := c.operationDefs[rpcName]; ok {
		operation, ok := operations[operationName]
		return operation, ok
	}
	return OperationDefinition{}, false
}

// proc invokes the given procedure and returns the raw wire envelope.
func (c *internalClient) proc(
	ctx context.Context,
	rpcName string,
	procName string,
	input any,
	opHeaderProviders []HeaderProvider,
	opRetryConf *RetryConfig,
	opTimeoutConf *TimeoutConfig,
) Response[json.RawMessage] {
	operation, ok := c.lookupOperation(rpcName, procName)
	if !ok {
		return Response[json.RawMessage]{
			Ok: false,
			Error: Error{
				Category: "ClientError",
				Code:     "INVALID_PROC",
				Message:  fmt.Sprintf("%s.%s procedure not found in schema", rpcName, procName),
				Details:  map[string]any{"rpc": rpcName, "procedure": procName},
			},
		}
	}

	reqInfo := RequestInfo{
		RPCName:       rpcName,
		OperationName: procName,
		Input:         input,
		Type:          OperationTypeProc,
		Annotations:   cloneAnnotations(operation.Annotations),
	}

	invoker := func(callCtx context.Context, req RequestInfo) (Response[json.RawMessage], error) {
		retryConf := c.mergeRetryConfig(req.RPCName, opRetryConf)
		timeoutConf := c.mergeTimeoutConfig(req.RPCName, opTimeoutConf)
		maxAttempts := retryConf.MaxAttempts
		if maxAttempts < 1 {
			maxAttempts = 1
		}

		payload, err := encodeRequestPayload(req.Input)
		if err != nil {
			return Response[json.RawMessage]{
				Ok: false,
				Error: Error{
					Category: "ClientError",
					Code:     "ENCODE_INPUT",
					Message:  fmt.Sprintf("failed to marshal input for %s.%s: %v", req.RPCName, req.OperationName, err),
				},
			}, nil
		}

		url := fmt.Sprintf("%s/%s/%s", c.baseURL, req.RPCName, req.OperationName)
		var last Response[json.RawMessage]

		for attempt := 1; attempt <= maxAttempts; attempt++ {
			attemptCtx := callCtx
			var cancel context.CancelFunc
			if timeoutConf.Timeout > 0 {
				attemptCtx, cancel = context.WithTimeout(callCtx, timeoutConf.Timeout)
			}

			res, defaultRetry, statusCode, decisionErr := c.doRequest(attemptCtx, req, url, payload, opHeaderProviders)
			if cancel != nil {
				cancel()
			}

			last = res
			shouldRetry := defaultRetry
			if retryConf.ShouldRetry != nil {
				shouldRetry = retryConf.ShouldRetry(callCtx, RetryDecisionContext{
					Request:        req,
					Attempt:        attempt,
					ResponseStatus: statusCode,
					Error:          decisionErr,
				})
			}

			if !shouldRetry || attempt >= maxAttempts {
				return res, nil
			}

			if err := waitForBackoff(callCtx, calculateBackoff(retryConf, attempt)); err != nil {
				return Response[json.RawMessage]{Ok: false, Error: ToError(err)}, nil
			}
		}

		return last, nil
	}

	res, err := c.executeChain(ctx, reqInfo, invoker)
	if err != nil {
		return Response[json.RawMessage]{Ok: false, Error: ToError(err)}
	}

	return res
}

// doRequest performs a single HTTP request attempt.
func (c *internalClient) doRequest(
	ctx context.Context,
	req RequestInfo,
	url string,
	payload []byte,
	opHeaderProviders []HeaderProvider,
) (Response[json.RawMessage], bool, int, error) {
	httpRequest, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(payload))
	if err != nil {
		wrapped := fmt.Errorf("failed to create HTTP request: %w", err)
		return Response[json.RawMessage]{Ok: false, Error: ToError(wrapped)}, false, 0, wrapped
	}

	httpRequest.Header.Set("Content-Type", "application/json")
	httpRequest.Header.Set("Accept", "application/json")

	if err := c.applyHeaderProviders(ctx, req.RPCName, httpRequest.Header, opHeaderProviders); err != nil {
		wrapped := fmt.Errorf("failed to apply headers: %w", err)
		return Response[json.RawMessage]{Ok: false, Error: ToError(wrapped)}, false, 0, wrapped
	}

	response, err := c.httpClient.Do(httpRequest)
	if err != nil {
		if errors.Is(ctx.Err(), context.Canceled) {
			wrapped := context.Canceled
			return Response[json.RawMessage]{Ok: false, Error: ToError(wrapped)}, false, 0, wrapped
		}

		if errors.Is(ctx.Err(), context.DeadlineExceeded) {
			timeoutErr := Error{
				Category: "TimeoutError",
				Code:     "REQUEST_TIMEOUT",
				Message:  "Request timeout",
			}
			return Response[json.RawMessage]{Ok: false, Error: timeoutErr}, true, 0, timeoutErr
		}

		wrapped := fmt.Errorf("http request failed: %w", err)
		return Response[json.RawMessage]{Ok: false, Error: ToError(wrapped)}, true, 0, wrapped
	}
	defer response.Body.Close()

	if response.StatusCode >= 500 {
		httpErr := Error{
			Category: "HTTPError",
			Code:     "BAD_STATUS",
			Message:  fmt.Sprintf("unexpected HTTP status: %s", response.Status),
			Details:  map[string]any{"status": response.StatusCode},
		}
		return Response[json.RawMessage]{Ok: false, Error: httpErr}, true, response.StatusCode, httpErr
	}

	if response.StatusCode < 200 || response.StatusCode >= 300 {
		httpErr := Error{
			Category: "HTTPError",
			Code:     "BAD_STATUS",
			Message:  fmt.Sprintf("unexpected HTTP status: %s", response.Status),
			Details:  map[string]any{"status": response.StatusCode},
		}
		return Response[json.RawMessage]{Ok: false, Error: httpErr}, false, response.StatusCode, httpErr
	}

	var raw struct {
		Ok     bool            `json:"ok"`
		Output json.RawMessage `json:"output"`
		Error  Error           `json:"error"`
	}

	if err := json.NewDecoder(response.Body).Decode(&raw); err != nil {
		wrapped := fmt.Errorf("failed to decode VDL response: %w", err)
		return Response[json.RawMessage]{Ok: false, Error: ToError(wrapped)}, false, response.StatusCode, wrapped
	}

	if !raw.Ok {
		return Response[json.RawMessage]{Ok: false, Error: raw.Error}, false, response.StatusCode, raw.Error
	}

	return Response[json.RawMessage]{Ok: true, Output: raw.Output}, false, response.StatusCode, nil
}

// applyHeaderProviders applies global, RPC-scoped, and per-operation header providers in order.
func (c *internalClient) applyHeaderProviders(ctx context.Context, rpcName string, header http.Header, opHeaderProviders []HeaderProvider) error {
	for _, provider := range c.headerProviders {
		if err := provider(ctx, header); err != nil {
			return fmt.Errorf("global header provider failed: %w", err)
		}
	}

	c.mu.RLock()
	rpcProviders := append([]HeaderProvider(nil), c.rpcHeaderProviders[rpcName]...)
	c.mu.RUnlock()

	for _, provider := range rpcProviders {
		if err := provider(ctx, header); err != nil {
			return fmt.Errorf("rpc header provider failed: %w", err)
		}
	}

	for _, provider := range opHeaderProviders {
		if err := provider(ctx, header); err != nil {
			return fmt.Errorf("operation header provider failed: %w", err)
		}
	}

	return nil
}

// stream establishes a Server-Sent Events subscription for the given stream.
func (c *internalClient) stream(ctx context.Context, rpcName string, streamName string, input any, opHeaderProviders []HeaderProvider, opReconnectConf *ReconnectConfig, opMaxMessageSize int64, onConnect func(), onDisconnect func(error), onReconnect func(int, time.Duration)) <-chan Response[json.RawMessage] {
	events := make(chan Response[json.RawMessage], 1)

	operation, ok := c.lookupOperation(rpcName, streamName)
	if !ok {
		errValue := Error{
			Category: "ClientError",
			Code:     "INVALID_STREAM",
			Message:  fmt.Sprintf("%s.%s stream not found in schema", rpcName, streamName),
			Details:  map[string]any{"rpc": rpcName, "stream": streamName},
		}
		events <- Response[json.RawMessage]{
			Ok:    false,
			Error: errValue,
		}
		close(events)
		if onDisconnect != nil {
			onDisconnect(errValue)
		}
		return events
	}

	reqInfo := RequestInfo{
		RPCName:       rpcName,
		OperationName: streamName,
		Input:         input,
		Type:          OperationTypeStream,
		Annotations:   cloneAnnotations(operation.Annotations),
	}

	invoker := func(callCtx context.Context, req RequestInfo) (Response[json.RawMessage], error) {
		reconnectConf := c.mergeReconnectConfig(req.RPCName, opReconnectConf)
		maxMessageSize := c.mergeMaxMessageSize(req.RPCName, opMaxMessageSize)
		payload, err := encodeRequestPayload(req.Input)
		if err != nil {
			errValue := ToError(fmt.Errorf("failed to marshal input for %s.%s: %w", req.RPCName, req.OperationName, err))
			events <- Response[json.RawMessage]{Ok: false, Error: errValue}
			close(events)
			if onDisconnect != nil {
				onDisconnect(errValue)
			}
			return Response[json.RawMessage]{Ok: false, Error: errValue}, nil
		}

		url := fmt.Sprintf("%s/%s/%s", c.baseURL, req.RPCName, req.OperationName)

		go func() {
			defer close(events)
			var finalErr error
			defer func() {
				if onDisconnect != nil {
					onDisconnect(finalErr)
				}
			}()

			reconnectAttempt := 0
			for {
				if callCtx.Err() != nil {
					finalErr = callCtx.Err()
					return
				}

				httpRequest, err := http.NewRequestWithContext(callCtx, http.MethodPost, url, bytes.NewReader(payload))
				if err != nil {
					finalErr = err
					events <- Response[json.RawMessage]{Ok: false, Error: ToError(err)}
					return
				}

				httpRequest.Header.Set("Content-Type", "application/json")
				httpRequest.Header.Set("Accept", "text/event-stream")

				if err := c.applyHeaderProviders(callCtx, req.RPCName, httpRequest.Header, opHeaderProviders); err != nil {
					finalErr = err
					events <- Response[json.RawMessage]{Ok: false, Error: ToError(err)}
					return
				}

				response, err := c.httpClient.Do(httpRequest)
				if err != nil {
					shouldReconnect := true
					if reconnectConf.ShouldReconnect != nil {
						shouldReconnect = reconnectConf.ShouldReconnect(callCtx, ReconnectDecisionContext{
							Request:        req,
							Attempt:        reconnectAttempt + 1,
							ResponseStatus: 0,
							Error:          err,
						})
					}

					if shouldReconnect && reconnectAttempt < reconnectConf.MaxAttempts {
						reconnectAttempt++
						delay := calculateReconnectBackoff(reconnectConf, reconnectAttempt)
						if onReconnect != nil {
							onReconnect(reconnectAttempt, delay)
						}
						if waitErr := waitForBackoff(callCtx, delay); waitErr != nil {
							finalErr = waitErr
							return
						}
						continue
					}

					finalErr = err
					events <- Response[json.RawMessage]{Ok: false, Error: ToError(err)}
					return
				}

				if response.StatusCode >= 500 {
					httpErr := Error{
						Category: "HTTPError",
						Code:     "BAD_STATUS",
						Message:  fmt.Sprintf("unexpected HTTP status: %s", response.Status),
						Details:  map[string]any{"status": response.StatusCode},
					}

					shouldReconnect := true
					if reconnectConf.ShouldReconnect != nil {
						shouldReconnect = reconnectConf.ShouldReconnect(callCtx, ReconnectDecisionContext{
							Request:        req,
							Attempt:        reconnectAttempt + 1,
							ResponseStatus: response.StatusCode,
							Error:          httpErr,
						})
					}
					response.Body.Close()

					if shouldReconnect && reconnectAttempt < reconnectConf.MaxAttempts {
						reconnectAttempt++
						delay := calculateReconnectBackoff(reconnectConf, reconnectAttempt)
						if onReconnect != nil {
							onReconnect(reconnectAttempt, delay)
						}
						if waitErr := waitForBackoff(callCtx, delay); waitErr != nil {
							finalErr = waitErr
							return
						}
						continue
					}

					finalErr = httpErr
					events <- Response[json.RawMessage]{Ok: false, Error: httpErr}
					return
				}

				if response.StatusCode < 200 || response.StatusCode >= 300 {
					httpErr := Error{
						Category: "HTTPError",
						Code:     "BAD_STATUS",
						Message:  fmt.Sprintf("unexpected HTTP status: %s", response.Status),
						Details:  map[string]any{"status": response.StatusCode},
					}
					response.Body.Close()
					finalErr = httpErr
					events <- Response[json.RawMessage]{Ok: false, Error: httpErr}
					return
				}

				if onConnect != nil {
					onConnect()
				}
				reconnectAttempt = 0

				result := handleStreamEvents(callCtx, response, maxMessageSize, events)
				response.Body.Close()

				if result.reconnectable {
					shouldReconnect := true
					if reconnectConf.ShouldReconnect != nil {
						shouldReconnect = reconnectConf.ShouldReconnect(callCtx, ReconnectDecisionContext{
							Request:        req,
							Attempt:        reconnectAttempt + 1,
							ResponseStatus: http.StatusOK,
							Error:          result.err,
						})
					}

					if shouldReconnect && reconnectAttempt < reconnectConf.MaxAttempts {
						reconnectAttempt++
						delay := calculateReconnectBackoff(reconnectConf, reconnectAttempt)
						if onReconnect != nil {
							onReconnect(reconnectAttempt, delay)
						}
						if waitErr := waitForBackoff(callCtx, delay); waitErr != nil {
							finalErr = waitErr
							return
						}
						continue
					}
				}

				if result.err != nil {
					finalErr = result.err
					if result.deliverErrorEvent {
						events <- Response[json.RawMessage]{Ok: false, Error: ToError(result.err)}
					}
				}
				return
			}
		}()

		return Response[json.RawMessage]{Ok: true}, nil
	}

	_, _ = c.executeChain(ctx, reqInfo, invoker)
	return events
}

// streamReadResult describes the outcome of processing an SSE response body.
type streamReadResult struct {
	reconnectable     bool
	deliverErrorEvent bool
	err               error
}

// handleStreamEvents consumes Server-Sent Events from the response body.
func handleStreamEvents(ctx context.Context, response *http.Response, maxMessageSize int64, events chan<- Response[json.RawMessage]) streamReadResult {
	scanner := bufio.NewScanner(response.Body)
	scanner.Buffer(make([]byte, 4096), int(maxMessageSize))

	var dataBuffer bytes.Buffer
	flush := func() {
		if dataBuffer.Len() == 0 {
			return
		}

		var event Response[json.RawMessage]
		if err := json.Unmarshal(dataBuffer.Bytes(), &event); err != nil {
			events <- Response[json.RawMessage]{
				Ok:    false,
				Error: ToError(fmt.Errorf("received invalid SSE payload: %w", err)),
			}
			dataBuffer.Reset()
			return
		}

		select {
		case events <- event:
		case <-ctx.Done():
		}

		dataBuffer.Reset()
	}

	for {
		select {
		case <-ctx.Done():
			return streamReadResult{}
		default:
		}

		if !scanner.Scan() {
			if err := scanner.Err(); err != nil {
				if err == bufio.ErrTooLong {
					return streamReadResult{
						reconnectable:     false,
						deliverErrorEvent: true,
						err: Error{
							Category: "ProtocolError",
							Code:     "MESSAGE_TOO_LARGE",
							Message:  fmt.Sprintf("stream message exceeded maximum size of %d bytes", maxMessageSize),
						},
					}
				}

				return streamReadResult{reconnectable: true, err: err}
			}

			return streamReadResult{}
		}

		line := scanner.Text()
		if line == "" {
			flush()
			continue
		}

		if strings.HasPrefix(line, ":") {
			continue
		}

		if strings.HasPrefix(line, "data:") {
			chunk := strings.TrimSpace(strings.TrimPrefix(line, "data:"))
			if int64(dataBuffer.Len()+len(chunk)) > maxMessageSize {
				return streamReadResult{
					reconnectable:     false,
					deliverErrorEvent: true,
					err: Error{
						Category: "ProtocolError",
						Code:     "MESSAGE_TOO_LARGE",
						Message:  fmt.Sprintf("stream message accumulation exceeded maximum size of %d bytes", maxMessageSize),
					},
				}
			}

			dataBuffer.WriteString(chunk)
		}
	}
}

// encodeRequestPayload marshals the request input using an empty JSON object when the input is nil.
func encodeRequestPayload(input any) ([]byte, error) {
	if input == nil {
		return []byte("{}"), nil
	}

	return json.Marshal(input)
}

// calculateBackoff computes the delay for a retry attempt.
func calculateBackoff(config *RetryConfig, attempt int) time.Duration {
	delay := config.InitialDelay
	for index := 1; index < attempt; index++ {
		delay = time.Duration(float64(delay) * config.DelayMultiplier)
	}

	if config.MaxDelay > 0 && delay > config.MaxDelay {
		delay = config.MaxDelay
	}

	return applyJitter(delay, config.Jitter)
}

// calculateReconnectBackoff computes the delay for a reconnect attempt.
func calculateReconnectBackoff(config *ReconnectConfig, attempt int) time.Duration {
	delay := config.InitialDelay
	for index := 1; index < attempt; index++ {
		delay = time.Duration(float64(delay) * config.DelayMultiplier)
	}

	if config.MaxDelay > 0 && delay > config.MaxDelay {
		delay = config.MaxDelay
	}

	return applyJitter(delay, config.Jitter)
}

// applyJitter applies bounded randomness to the given delay.
func applyJitter(delay time.Duration, factor float64) time.Duration {
	if factor <= 0 || delay <= 0 {
		return delay
	}

	if factor > 1 {
		factor = 1
	}

	delta := float64(delay) * factor
	minimum := float64(delay) - delta
	maximum := float64(delay) + delta
	if minimum < 0 {
		minimum = 0
	}

	return time.Duration(minimum + (rand.Float64() * (maximum - minimum)))
}

// waitForBackoff waits for the given delay or returns when the context is cancelled.
func waitForBackoff(ctx context.Context, delay time.Duration) error {
	if delay <= 0 {
		return nil
	}

	timer := time.NewTimer(delay)
	defer timer.Stop()

	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

// -----------------------------------------------------------------------------
// Client Builder
// -----------------------------------------------------------------------------

// clientBuilder collects configuration before a generated client is built.
type clientBuilder struct {
	baseURL string
	opts    []internalClientOption
}

// WithHTTPClient supplies a custom HTTP client implementation.
func (b *clientBuilder) WithHTTPClient(client *http.Client) *clientBuilder {
	b.opts = append(b.opts, withHTTPClient(client))
	return b
}

// WithHeader registers a static header that is sent with every request.
func (b *clientBuilder) WithHeader(key string, value string) *clientBuilder {
	b.opts = append(b.opts, withGlobalHeader(key, value))
	return b
}

// WithHeaderProvider registers a dynamic header provider.
func (b *clientBuilder) WithHeaderProvider(provider HeaderProvider) *clientBuilder {
	b.opts = append(b.opts, withHeaderProvider(provider))
	return b
}

// WithInterceptor registers a transport interceptor.
func (b *clientBuilder) WithInterceptor(interceptor Interceptor) *clientBuilder {
	b.opts = append(b.opts, withInterceptor(interceptor))
	return b
}

// WithRetryConfig sets the default retry configuration for procedures.
func (b *clientBuilder) WithRetryConfig(conf RetryConfig) *clientBuilder {
	b.opts = append(b.opts, withGlobalRetryConfig(conf))
	return b
}

// WithTimeoutConfig sets the default timeout configuration for procedures.
func (b *clientBuilder) WithTimeoutConfig(conf TimeoutConfig) *clientBuilder {
	b.opts = append(b.opts, withGlobalTimeoutConfig(conf))
	return b
}

// WithReconnectConfig sets the default reconnect configuration for streams.
func (b *clientBuilder) WithReconnectConfig(conf ReconnectConfig) *clientBuilder {
	b.opts = append(b.opts, withGlobalReconnectConfig(conf))
	return b
}

// WithMaxMessageSize sets the default maximum message size for streams.
func (b *clientBuilder) WithMaxMessageSize(size int64) *clientBuilder {
	b.opts = append(b.opts, withGlobalMaxMessageSize(size))
	return b
}

// Build creates the generated RPC client.
func (b *clientBuilder) Build() *Client {
	intClient := newInternalClient(b.baseURL, VDLProcedures, VDLStreams, b.opts...)
	return &Client{RPCs: &clientRPCRegistry{intClient: intClient}}
}

// -----------------------------------------------------------------------------
// Client Implementation
// -----------------------------------------------------------------------------

// Client is the public entrypoint for generated RPC calls.
type Client struct {
	RPCs *clientRPCRegistry
}

// NewClient creates a new generated RPC client builder.
func NewClient(baseURL string) *clientBuilder {
	return &clientBuilder{baseURL: baseURL, opts: []internalClientOption{}}
}

// clientRPCRegistry exposes the generated RPC services.
type clientRPCRegistry struct {
	intClient *internalClient
}

// Database returns the client registry for the Database RPC service.
func (r *clientRPCRegistry) Database() *clientDatabaseRPC {
	return &clientDatabaseRPC{
		intClient: r.intClient,
		Procs:     &clientDatabaseProcs{intClient: r.intClient},
		Streams:   &clientDatabaseStreams{intClient: r.intClient},
	}
}

// clientDatabaseRPC groups the generated client builders for the Database RPC service.
type clientDatabaseRPC struct {
	intClient *internalClient
	Procs     *clientDatabaseProcs
	Streams   *clientDatabaseStreams
}

// WithRetryConfig sets the default retry configuration for every procedure in the Database RPC service.
func (r *clientDatabaseRPC) WithRetryConfig(conf RetryConfig) *clientDatabaseRPC {
	r.intClient.setRPCRetryConfig("Database", conf)
	return r
}

// WithTimeoutConfig sets the default timeout configuration for every procedure in the Database RPC service.
func (r *clientDatabaseRPC) WithTimeoutConfig(conf TimeoutConfig) *clientDatabaseRPC {
	r.intClient.setRPCTimeoutConfig("Database", conf)
	return r
}

// WithReconnectConfig sets the default reconnect configuration for every stream in the Database RPC service.
func (r *clientDatabaseRPC) WithReconnectConfig(conf ReconnectConfig) *clientDatabaseRPC {
	r.intClient.setRPCReconnectConfig("Database", conf)
	return r
}

// WithMaxMessageSize sets the default maximum stream message size for the Database RPC service.
func (r *clientDatabaseRPC) WithMaxMessageSize(size int64) *clientDatabaseRPC {
	r.intClient.setRPCMaxMessageSize("Database", size)
	return r
}

// WithHeaderProvider adds a header provider for every request in the Database RPC service.
func (r *clientDatabaseRPC) WithHeaderProvider(provider HeaderProvider) *clientDatabaseRPC {
	r.intClient.setRPCHeaderProvider("Database", provider)
	return r
}

// WithHeader adds a static header for every request in the Database RPC service.
func (r *clientDatabaseRPC) WithHeader(key string, value string) *clientDatabaseRPC {
	r.intClient.setRPCHeaderProvider("Database", func(_ context.Context, h http.Header) error {
		h.Set(key, value)
		return nil
	})
	return r
}

// clientDatabaseProcs exposes the generated procedure builders for the Database RPC service.
type clientDatabaseProcs struct {
	intClient *internalClient
}

// Query creates a call builder for the Database.query procedure.
//
// Executes one or more SQL queries against the database.
//
// Queries are executed in order and each query returns one result item.
// Empty or failed queries are returned as result items with type "error".
func (registry *clientDatabaseProcs) Query() *clientBuilderDatabaseQuery {
	return &clientBuilderDatabaseQuery{client: registry.intClient, headerProviders: []HeaderProvider{}, rpcName: "Database", name: "query"}
}

// clientBuilderDatabaseQuery configures and executes calls to the Database.query procedure.
type clientBuilderDatabaseQuery struct {
	rpcName         string
	name            string
	client          *internalClient
	headerProviders []HeaderProvider
	retryConf       *RetryConfig
	timeoutConf     *TimeoutConfig
}

// WithHeader adds a static header to the Database.query procedure call.
func (b *clientBuilderDatabaseQuery) WithHeader(key string, value string) *clientBuilderDatabaseQuery {
	b.headerProviders = append(b.headerProviders, func(_ context.Context, h http.Header) error {
		h.Set(key, value)
		return nil
	})
	return b
}

// WithHeaderProvider adds a dynamic header provider to the Database.query procedure call.
func (b *clientBuilderDatabaseQuery) WithHeaderProvider(provider HeaderProvider) *clientBuilderDatabaseQuery {
	b.headerProviders = append(b.headerProviders, provider)
	return b
}

// WithRetryConfig overrides retry behavior for the Database.query procedure call.
func (b *clientBuilderDatabaseQuery) WithRetryConfig(conf RetryConfig) *clientBuilderDatabaseQuery {
	b.retryConf = &conf
	return b
}

// WithTimeoutConfig overrides timeout behavior for the Database.query procedure call.
func (b *clientBuilderDatabaseQuery) WithTimeoutConfig(conf TimeoutConfig) *clientBuilderDatabaseQuery {
	b.timeoutConf = &conf
	return b
}

// Execute sends a request to the Database.query procedure.
func (b *clientBuilderDatabaseQuery) Execute(ctx context.Context, input DatabaseQueryInput) (DatabaseQueryOutput, error) {
	raw := b.client.proc(ctx, b.rpcName, b.name, input, b.headerProviders, b.retryConf, b.timeoutConf)
	if !raw.Ok {
		return DatabaseQueryOutput{}, raw.Error
	}
	var out DatabaseQueryOutput
	if err := json.Unmarshal(raw.Output, &out); err != nil {
		return DatabaseQueryOutput{}, Error{Message: fmt.Sprintf("failed to decode Database.query output: %v", err)}
	}
	return out, nil
}

// clientDatabaseStreams exposes the generated stream builders for the Database RPC service.
type clientDatabaseStreams struct {
	intClient *internalClient
}

// System returns the client registry for the System RPC service.
func (r *clientRPCRegistry) System() *clientSystemRPC {
	return &clientSystemRPC{
		intClient: r.intClient,
		Procs:     &clientSystemProcs{intClient: r.intClient},
		Streams:   &clientSystemStreams{intClient: r.intClient},
	}
}

// clientSystemRPC groups the generated client builders for the System RPC service.
type clientSystemRPC struct {
	intClient *internalClient
	Procs     *clientSystemProcs
	Streams   *clientSystemStreams
}

// WithRetryConfig sets the default retry configuration for every procedure in the System RPC service.
func (r *clientSystemRPC) WithRetryConfig(conf RetryConfig) *clientSystemRPC {
	r.intClient.setRPCRetryConfig("System", conf)
	return r
}

// WithTimeoutConfig sets the default timeout configuration for every procedure in the System RPC service.
func (r *clientSystemRPC) WithTimeoutConfig(conf TimeoutConfig) *clientSystemRPC {
	r.intClient.setRPCTimeoutConfig("System", conf)
	return r
}

// WithReconnectConfig sets the default reconnect configuration for every stream in the System RPC service.
func (r *clientSystemRPC) WithReconnectConfig(conf ReconnectConfig) *clientSystemRPC {
	r.intClient.setRPCReconnectConfig("System", conf)
	return r
}

// WithMaxMessageSize sets the default maximum stream message size for the System RPC service.
func (r *clientSystemRPC) WithMaxMessageSize(size int64) *clientSystemRPC {
	r.intClient.setRPCMaxMessageSize("System", size)
	return r
}

// WithHeaderProvider adds a header provider for every request in the System RPC service.
func (r *clientSystemRPC) WithHeaderProvider(provider HeaderProvider) *clientSystemRPC {
	r.intClient.setRPCHeaderProvider("System", provider)
	return r
}

// WithHeader adds a static header for every request in the System RPC service.
func (r *clientSystemRPC) WithHeader(key string, value string) *clientSystemRPC {
	r.intClient.setRPCHeaderProvider("System", func(_ context.Context, h http.Header) error {
		h.Set(key, value)
		return nil
	})
	return r
}

// clientSystemProcs exposes the generated procedure builders for the System RPC service.
type clientSystemProcs struct {
	intClient *internalClient
}

// Health creates a call builder for the System.health procedure.
//
// Checks whether the server can perform a basic database read.
func (registry *clientSystemProcs) Health() *clientBuilderSystemHealth {
	return &clientBuilderSystemHealth{client: registry.intClient, headerProviders: []HeaderProvider{}, rpcName: "System", name: "health"}
}

// clientBuilderSystemHealth configures and executes calls to the System.health procedure.
type clientBuilderSystemHealth struct {
	rpcName         string
	name            string
	client          *internalClient
	headerProviders []HeaderProvider
	retryConf       *RetryConfig
	timeoutConf     *TimeoutConfig
}

// WithHeader adds a static header to the System.health procedure call.
func (b *clientBuilderSystemHealth) WithHeader(key string, value string) *clientBuilderSystemHealth {
	b.headerProviders = append(b.headerProviders, func(_ context.Context, h http.Header) error {
		h.Set(key, value)
		return nil
	})
	return b
}

// WithHeaderProvider adds a dynamic header provider to the System.health procedure call.
func (b *clientBuilderSystemHealth) WithHeaderProvider(provider HeaderProvider) *clientBuilderSystemHealth {
	b.headerProviders = append(b.headerProviders, provider)
	return b
}

// WithRetryConfig overrides retry behavior for the System.health procedure call.
func (b *clientBuilderSystemHealth) WithRetryConfig(conf RetryConfig) *clientBuilderSystemHealth {
	b.retryConf = &conf
	return b
}

// WithTimeoutConfig overrides timeout behavior for the System.health procedure call.
func (b *clientBuilderSystemHealth) WithTimeoutConfig(conf TimeoutConfig) *clientBuilderSystemHealth {
	b.timeoutConf = &conf
	return b
}

// Execute sends a request to the System.health procedure.
func (b *clientBuilderSystemHealth) Execute(ctx context.Context, input Void) (SystemHealthOutput, error) {
	raw := b.client.proc(ctx, b.rpcName, b.name, input, b.headerProviders, b.retryConf, b.timeoutConf)
	if !raw.Ok {
		return SystemHealthOutput{}, raw.Error
	}
	var out SystemHealthOutput
	if err := json.Unmarshal(raw.Output, &out); err != nil {
		return SystemHealthOutput{}, Error{Message: fmt.Sprintf("failed to decode System.health output: %v", err)}
	}
	return out, nil
}

// Session creates a call builder for the System.session procedure.
//
// Returns the authentication role for the current session.
func (registry *clientSystemProcs) Session() *clientBuilderSystemSession {
	return &clientBuilderSystemSession{client: registry.intClient, headerProviders: []HeaderProvider{}, rpcName: "System", name: "session"}
}

// clientBuilderSystemSession configures and executes calls to the System.session procedure.
type clientBuilderSystemSession struct {
	rpcName         string
	name            string
	client          *internalClient
	headerProviders []HeaderProvider
	retryConf       *RetryConfig
	timeoutConf     *TimeoutConfig
}

// WithHeader adds a static header to the System.session procedure call.
func (b *clientBuilderSystemSession) WithHeader(key string, value string) *clientBuilderSystemSession {
	b.headerProviders = append(b.headerProviders, func(_ context.Context, h http.Header) error {
		h.Set(key, value)
		return nil
	})
	return b
}

// WithHeaderProvider adds a dynamic header provider to the System.session procedure call.
func (b *clientBuilderSystemSession) WithHeaderProvider(provider HeaderProvider) *clientBuilderSystemSession {
	b.headerProviders = append(b.headerProviders, provider)
	return b
}

// WithRetryConfig overrides retry behavior for the System.session procedure call.
func (b *clientBuilderSystemSession) WithRetryConfig(conf RetryConfig) *clientBuilderSystemSession {
	b.retryConf = &conf
	return b
}

// WithTimeoutConfig overrides timeout behavior for the System.session procedure call.
func (b *clientBuilderSystemSession) WithTimeoutConfig(conf TimeoutConfig) *clientBuilderSystemSession {
	b.timeoutConf = &conf
	return b
}

// Execute sends a request to the System.session procedure.
func (b *clientBuilderSystemSession) Execute(ctx context.Context, input Void) (SystemSessionOutput, error) {
	raw := b.client.proc(ctx, b.rpcName, b.name, input, b.headerProviders, b.retryConf, b.timeoutConf)
	if !raw.Ok {
		return SystemSessionOutput{}, raw.Error
	}
	var out SystemSessionOutput
	if err := json.Unmarshal(raw.Output, &out); err != nil {
		return SystemSessionOutput{}, Error{Message: fmt.Sprintf("failed to decode System.session output: %v", err)}
	}
	return out, nil
}

// Status creates a call builder for the System.status procedure.
//
// Returns server information and runtime statistics.
func (registry *clientSystemProcs) Status() *clientBuilderSystemStatus {
	return &clientBuilderSystemStatus{client: registry.intClient, headerProviders: []HeaderProvider{}, rpcName: "System", name: "status"}
}

// clientBuilderSystemStatus configures and executes calls to the System.status procedure.
type clientBuilderSystemStatus struct {
	rpcName         string
	name            string
	client          *internalClient
	headerProviders []HeaderProvider
	retryConf       *RetryConfig
	timeoutConf     *TimeoutConfig
}

// WithHeader adds a static header to the System.status procedure call.
func (b *clientBuilderSystemStatus) WithHeader(key string, value string) *clientBuilderSystemStatus {
	b.headerProviders = append(b.headerProviders, func(_ context.Context, h http.Header) error {
		h.Set(key, value)
		return nil
	})
	return b
}

// WithHeaderProvider adds a dynamic header provider to the System.status procedure call.
func (b *clientBuilderSystemStatus) WithHeaderProvider(provider HeaderProvider) *clientBuilderSystemStatus {
	b.headerProviders = append(b.headerProviders, provider)
	return b
}

// WithRetryConfig overrides retry behavior for the System.status procedure call.
func (b *clientBuilderSystemStatus) WithRetryConfig(conf RetryConfig) *clientBuilderSystemStatus {
	b.retryConf = &conf
	return b
}

// WithTimeoutConfig overrides timeout behavior for the System.status procedure call.
func (b *clientBuilderSystemStatus) WithTimeoutConfig(conf TimeoutConfig) *clientBuilderSystemStatus {
	b.timeoutConf = &conf
	return b
}

// Execute sends a request to the System.status procedure.
func (b *clientBuilderSystemStatus) Execute(ctx context.Context, input Void) (SystemStatusOutput, error) {
	raw := b.client.proc(ctx, b.rpcName, b.name, input, b.headerProviders, b.retryConf, b.timeoutConf)
	if !raw.Ok {
		return SystemStatusOutput{}, raw.Error
	}
	var out SystemStatusOutput
	if err := json.Unmarshal(raw.Output, &out); err != nil {
		return SystemStatusOutput{}, Error{Message: fmt.Sprintf("failed to decode System.status output: %v", err)}
	}
	return out, nil
}

// clientSystemStreams exposes the generated stream builders for the System RPC service.
type clientSystemStreams struct {
	intClient *internalClient
}
