// Code generated by VDL v0.5.0-alpha.5 (commit 1aaf1f7) using varavelio/vdl-plugin-go@v0.1.3 (hash fb864874)
// Any changes will be overwritten the next time VDL is run. DO NOT EDIT.
// Learn more: https://github.com/varavelio/vdl

package vdl

import (
	"fmt"
	json "github.com/goccy/go-json"
)

// AuthRole defines a generated enum.
type AuthRole string

// AuthRole constants define the declared values of AuthRole.
const (
	// Full administrative access.
	AuthRoleAdmin AuthRole = "admin"
	// Read and write access to the database.
	AuthRoleReadWrite AuthRole = "rw"
	// Read-only access to the database.
	AuthRoleReadOnly AuthRole = "ro"
)

// AuthRoleList contains every valid AuthRole value.
var AuthRoleList = []AuthRole{
	AuthRoleAdmin,
	AuthRoleReadWrite,
	AuthRoleReadOnly,
}

// String returns a readable representation of AuthRole.
func (e AuthRole) String() string {
	return string(e)
}

// IsValid reports whether the value belongs to AuthRole.
func (e AuthRole) IsValid() bool {
	switch e {
	case AuthRoleAdmin, AuthRoleReadWrite, AuthRoleReadOnly:
		return true
	}
	return false
}

// MarshalJSON encodes AuthRole and rejects values outside the declared enum set.
func (e AuthRole) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid value %q for AuthRole enum", string(e))
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON decodes AuthRole and rejects values outside the declared enum set.
func (e *AuthRole) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	candidate := AuthRole(value)
	if !candidate.IsValid() {
		return fmt.Errorf("invalid value %q for AuthRole enum", value)
	}
	*e = candidate
	return nil
}

// QueryResultType defines a generated enum.
type QueryResultType string

// QueryResultType constants define the declared values of QueryResultType.
const (
	// A read-only query (SELECT).
	QueryResultTypeRead QueryResultType = "read"
	// A write query (INSERT, UPDATE, DELETE, CREATE, etc.).
	QueryResultTypeWrite QueryResultType = "write"
	// A BEGIN TRANSACTION query.
	QueryResultTypeBegin QueryResultType = "begin"
	// A COMMIT TRANSACTION query.
	QueryResultTypeCommit QueryResultType = "commit"
	// A ROLLBACK TRANSACTION query.
	QueryResultTypeRollback QueryResultType = "rollback"
	// An error result produced by an empty or failed query.
	QueryResultTypeError QueryResultType = "error"
)

// QueryResultTypeList contains every valid QueryResultType value.
var QueryResultTypeList = []QueryResultType{
	QueryResultTypeRead,
	QueryResultTypeWrite,
	QueryResultTypeBegin,
	QueryResultTypeCommit,
	QueryResultTypeRollback,
	QueryResultTypeError,
}

// String returns a readable representation of QueryResultType.
func (e QueryResultType) String() string {
	return string(e)
}

// IsValid reports whether the value belongs to QueryResultType.
func (e QueryResultType) IsValid() bool {
	switch e {
	case QueryResultTypeRead, QueryResultTypeWrite, QueryResultTypeBegin, QueryResultTypeCommit, QueryResultTypeRollback, QueryResultTypeError:
		return true
	}
	return false
}

// MarshalJSON encodes QueryResultType and rejects values outside the declared enum set.
func (e QueryResultType) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid value %q for QueryResultType enum", string(e))
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON decodes QueryResultType and rejects values outside the declared enum set.
func (e *QueryResultType) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	candidate := QueryResultType(value)
	if !candidate.IsValid() {
		return fmt.Errorf("invalid value %q for QueryResultType enum", value)
	}
	*e = candidate
	return nil
}

// SqliteStorageClass defines a generated enum.
type SqliteStorageClass string

// SqliteStorageClass constants define the declared values of SqliteStorageClass.
const (
	// The SQL NULL value.
	SqliteStorageClassNull SqliteStorageClass = "NULL"
	// A signed integer.
	SqliteStorageClassInteger SqliteStorageClass = "INTEGER"
	// A floating-point value.
	SqliteStorageClassReal SqliteStorageClass = "REAL"
	// A text string.
	SqliteStorageClassText SqliteStorageClass = "TEXT"
	// A binary blob.
	SqliteStorageClassBlob SqliteStorageClass = "BLOB"
)

// SqliteStorageClassList contains every valid SqliteStorageClass value.
var SqliteStorageClassList = []SqliteStorageClass{
	SqliteStorageClassNull,
	SqliteStorageClassInteger,
	SqliteStorageClassReal,
	SqliteStorageClassText,
	SqliteStorageClassBlob,
}

// String returns a readable representation of SqliteStorageClass.
func (e SqliteStorageClass) String() string {
	return string(e)
}

// IsValid reports whether the value belongs to SqliteStorageClass.
func (e SqliteStorageClass) IsValid() bool {
	switch e {
	case SqliteStorageClassNull, SqliteStorageClassInteger, SqliteStorageClassReal, SqliteStorageClassText, SqliteStorageClassBlob:
		return true
	}
	return false
}

// MarshalJSON encodes SqliteStorageClass and rejects values outside the declared enum set.
func (e SqliteStorageClass) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid value %q for SqliteStorageClass enum", string(e))
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON decodes SqliteStorageClass and rejects values outside the declared enum set.
func (e *SqliteStorageClass) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	candidate := SqliteStorageClass(value)
	if !candidate.IsValid() {
		return fmt.Errorf("invalid value %q for SqliteStorageClass enum", value)
	}
	*e = candidate
	return nil
}
