// Code generated by VDL v0.5.0-alpha.5 (commit 1aaf1f7) using varavelio/vdl-plugin-go@v0.1.3 (hash fb864874)
// Any changes will be overwritten the next time VDL is run. DO NOT EDIT.
// Learn more: https://github.com/varavelio/vdl

package vdl

// Ptr returns a pointer to the provided value.
func Ptr[T any](value T) *T {
	return &value
}

// Val dereferences a pointer or returns the zero value when it is nil.
func Val[T any](pointer *T) T {
	if pointer == nil {
		var zero T
		return zero
	}
	return *pointer
}

// Or dereferences a pointer or returns the provided default when it is nil.
func Or[T any](pointer *T, defaultValue T) T {
	if pointer == nil {
		return defaultValue
	}
	return *pointer
}
