// Code generated by VDL v0.5.0-alpha.5 (commit 1aaf1f7) using varavelio/vdl-plugin-go@v0.1.3 (hash fb864874)
// Any changes will be overwritten the next time VDL is run. DO NOT EDIT.
// Learn more: https://github.com/varavelio/vdl

package vdl

import (
	"fmt"
	json "github.com/goccy/go-json"
	"time"
)

// Database represents a VDL object.
type Database struct {
	// Executes one or more SQL queries against the database.
	//
	// Queries are executed in order and each query returns one result item.
	// Empty or failed queries are returned as result items with type "error".
	Query DatabaseQuery `json:"query"`
}

// preDatabase mirrors Database during strict JSON decoding.
type preDatabase struct {
	Query *preDatabaseQuery `json:"query"`
}

// validate reports whether preDatabase satisfies strict JSON requirements.
func (p *preDatabase) validate(parentPath string) error {
	vdlPathQuery := "query"
	if parentPath != "" {
		vdlPathQuery = parentPath + ".query"
	}
	if p.Query == nil {
		return fmt.Errorf("field %s is required", vdlPathQuery)
	}
	if p.Query != nil {
		if err := p.Query.validate(vdlPathQuery); err != nil {
			return err
		}
	}
	return nil
}

// transform converts preDatabase to Database.
func (p *preDatabase) transform() Database {
	var transQuery DatabaseQuery
	transQuery = DatabaseQuery(p.Query.transform())

	return Database{
		Query: transQuery,
	}
}

// UnmarshalJSON decodes Database while requiring every non-optional JSON field.
func (x *Database) UnmarshalJSON(data []byte) error {
	var pre preDatabase
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetQuery returns the Query field. It returns the zero value when the receiver is nil.
func (x *Database) GetQuery() DatabaseQuery {
	if x != nil {
		return x.Query
	}
	var zero DatabaseQuery
	return zero
}

// GetQueryOr returns the Query field. It returns defaultValue when the receiver is nil.
func (x *Database) GetQueryOr(defaultValue DatabaseQuery) DatabaseQuery {
	if x != nil {
		return x.Query
	}
	return defaultValue
}

// DatabaseQuery represents the inline object declared at Database.query.
type DatabaseQuery struct {
	Input  DatabaseQueryInput  `json:"input"`
	Output DatabaseQueryOutput `json:"output"`
}

// preDatabaseQuery mirrors DatabaseQuery during strict JSON decoding.
type preDatabaseQuery struct {
	Input  *preDatabaseQueryInput  `json:"input"`
	Output *preDatabaseQueryOutput `json:"output"`
}

// validate reports whether preDatabaseQuery satisfies strict JSON requirements.
func (p *preDatabaseQuery) validate(parentPath string) error {
	vdlPathInput := "input"
	if parentPath != "" {
		vdlPathInput = parentPath + ".input"
	}
	if p.Input == nil {
		return fmt.Errorf("field %s is required", vdlPathInput)
	}
	if p.Input != nil {
		if err := p.Input.validate(vdlPathInput); err != nil {
			return err
		}
	}

	vdlPathOutput := "output"
	if parentPath != "" {
		vdlPathOutput = parentPath + ".output"
	}
	if p.Output == nil {
		return fmt.Errorf("field %s is required", vdlPathOutput)
	}
	if p.Output != nil {
		if err := p.Output.validate(vdlPathOutput); err != nil {
			return err
		}
	}
	return nil
}

// transform converts preDatabaseQuery to DatabaseQuery.
func (p *preDatabaseQuery) transform() DatabaseQuery {
	var transInput DatabaseQueryInput
	transInput = DatabaseQueryInput(p.Input.transform())

	var transOutput DatabaseQueryOutput
	transOutput = DatabaseQueryOutput(p.Output.transform())

	return DatabaseQuery{
		Input:  transInput,
		Output: transOutput,
	}
}

// UnmarshalJSON decodes DatabaseQuery while requiring every non-optional JSON field.
func (x *DatabaseQuery) UnmarshalJSON(data []byte) error {
	var pre preDatabaseQuery
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetInput returns the Input field. It returns the zero value when the receiver is nil.
func (x *DatabaseQuery) GetInput() DatabaseQueryInput {
	if x != nil {
		return x.Input
	}
	var zero DatabaseQueryInput
	return zero
}

// GetInputOr returns the Input field. It returns defaultValue when the receiver is nil.
func (x *DatabaseQuery) GetInputOr(defaultValue DatabaseQueryInput) DatabaseQueryInput {
	if x != nil {
		return x.Input
	}
	return defaultValue
}

// GetOutput returns the Output field. It returns the zero value when the receiver is nil.
func (x *DatabaseQuery) GetOutput() DatabaseQueryOutput {
	if x != nil {
		return x.Output
	}
	var zero DatabaseQueryOutput
	return zero
}

// GetOutputOr returns the Output field. It returns defaultValue when the receiver is nil.
func (x *DatabaseQuery) GetOutputOr(defaultValue DatabaseQueryOutput) DatabaseQueryOutput {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// DatabaseQueryInput represents the inline object declared at Database.query.input.
type DatabaseQueryInput struct {
	// The list of SQL queries to execute in order.
	Queries []Query `json:"queries"`
}

// preDatabaseQueryInput mirrors DatabaseQueryInput during strict JSON decoding.
type preDatabaseQueryInput struct {
	Queries *[]preQuery `json:"queries"`
}

// validate reports whether preDatabaseQueryInput satisfies strict JSON requirements.
func (p *preDatabaseQueryInput) validate(parentPath string) error {
	vdlPathQueries := "queries"
	if parentPath != "" {
		vdlPathQueries = parentPath + ".queries"
	}
	if p.Queries == nil {
		return fmt.Errorf("field %s is required", vdlPathQueries)
	}
	if p.Queries != nil {
		for vdlIndex0, vdlItem0 := range *p.Queries {
			vdlItemPath0 := fmt.Sprintf("%s[%d]", vdlPathQueries, vdlIndex0)
			if err := vdlItem0.validate(vdlItemPath0); err != nil {
				return err
			}
		}
	}
	return nil
}

// transform converts preDatabaseQueryInput to DatabaseQueryInput.
func (p *preDatabaseQueryInput) transform() DatabaseQueryInput {
	var transQueries []Query
	transQueries = make([]Query, len(*p.Queries))
	for vdlIndex0, vdlItem0 := range *p.Queries {
		var vdlTransformed0 Query
		vdlTransformed0 = Query(vdlItem0.transform())
		transQueries[vdlIndex0] = vdlTransformed0
	}

	return DatabaseQueryInput{
		Queries: transQueries,
	}
}

// UnmarshalJSON decodes DatabaseQueryInput while requiring every non-optional JSON field.
func (x *DatabaseQueryInput) UnmarshalJSON(data []byte) error {
	var pre preDatabaseQueryInput
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetQueries returns the Queries field. It returns the zero value when the receiver is nil.
func (x *DatabaseQueryInput) GetQueries() []Query {
	if x != nil {
		return x.Queries
	}
	var zero []Query
	return zero
}

// GetQueriesOr returns the Queries field. It returns defaultValue when the receiver is nil.
func (x *DatabaseQueryInput) GetQueriesOr(defaultValue []Query) []Query {
	if x != nil {
		return x.Queries
	}
	return defaultValue
}

// DatabaseQueryOutput represents the inline object declared at Database.query.output.
type DatabaseQueryOutput struct {
	// Total execution time in seconds for all queries.
	Time float64 `json:"time"`
	// One result per input query, in the same order.
	Results []QueryResult `json:"results"`
}

// preDatabaseQueryOutput mirrors DatabaseQueryOutput during strict JSON decoding.
type preDatabaseQueryOutput struct {
	Time    *float64          `json:"time"`
	Results *[]preQueryResult `json:"results"`
}

// validate reports whether preDatabaseQueryOutput satisfies strict JSON requirements.
func (p *preDatabaseQueryOutput) validate(parentPath string) error {
	vdlPathTime := "time"
	if parentPath != "" {
		vdlPathTime = parentPath + ".time"
	}
	if p.Time == nil {
		return fmt.Errorf("field %s is required", vdlPathTime)
	}

	vdlPathResults := "results"
	if parentPath != "" {
		vdlPathResults = parentPath + ".results"
	}
	if p.Results == nil {
		return fmt.Errorf("field %s is required", vdlPathResults)
	}
	if p.Results != nil {
		for vdlIndex0, vdlItem0 := range *p.Results {
			vdlItemPath0 := fmt.Sprintf("%s[%d]", vdlPathResults, vdlIndex0)
			if err := vdlItem0.validate(vdlItemPath0); err != nil {
				return err
			}
		}
	}
	return nil
}

// transform converts preDatabaseQueryOutput to DatabaseQueryOutput.
func (p *preDatabaseQueryOutput) transform() DatabaseQueryOutput {
	var transTime float64
	transTime = *p.Time

	var transResults []QueryResult
	transResults = make([]QueryResult, len(*p.Results))
	for vdlIndex0, vdlItem0 := range *p.Results {
		var vdlTransformed0 QueryResult
		vdlTransformed0 = QueryResult(vdlItem0.transform())
		transResults[vdlIndex0] = vdlTransformed0
	}

	return DatabaseQueryOutput{
		Time:    transTime,
		Results: transResults,
	}
}

// UnmarshalJSON decodes DatabaseQueryOutput while requiring every non-optional JSON field.
func (x *DatabaseQueryOutput) UnmarshalJSON(data []byte) error {
	var pre preDatabaseQueryOutput
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetTime returns the Time field. It returns the zero value when the receiver is nil.
func (x *DatabaseQueryOutput) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	var zero float64
	return zero
}

// GetTimeOr returns the Time field. It returns defaultValue when the receiver is nil.
func (x *DatabaseQueryOutput) GetTimeOr(defaultValue float64) float64 {
	if x != nil {
		return x.Time
	}
	return defaultValue
}

// GetResults returns the Results field. It returns the zero value when the receiver is nil.
func (x *DatabaseQueryOutput) GetResults() []QueryResult {
	if x != nil {
		return x.Results
	}
	var zero []QueryResult
	return zero
}

// GetResultsOr returns the Results field. It returns defaultValue when the receiver is nil.
func (x *DatabaseQueryOutput) GetResultsOr(defaultValue []QueryResult) []QueryResult {
	if x != nil {
		return x.Results
	}
	return defaultValue
}

// Query represents a VDL object.
type Query struct {
	// Transaction ID to execute the query within an existing transaction.
	TxId *string `json:"txId,omitempty"`
	// The SQL query string.
	Query string `json:"query"`
	// Optional query parameters.
	Params *[]QueryParam `json:"params,omitempty"`
}

// preQuery mirrors Query during strict JSON decoding.
type preQuery struct {
	TxId   *string          `json:"txId,omitempty"`
	Query  *string          `json:"query"`
	Params *[]preQueryParam `json:"params,omitempty"`
}

// validate reports whether preQuery satisfies strict JSON requirements.
func (p *preQuery) validate(parentPath string) error {
	vdlPathQuery := "query"
	if parentPath != "" {
		vdlPathQuery = parentPath + ".query"
	}
	if p.Query == nil {
		return fmt.Errorf("field %s is required", vdlPathQuery)
	}

	vdlPathParams := "params"
	if parentPath != "" {
		vdlPathParams = parentPath + ".params"
	}
	if p.Params != nil {
		for vdlIndex0, vdlItem0 := range *p.Params {
			vdlItemPath0 := fmt.Sprintf("%s[%d]", vdlPathParams, vdlIndex0)
			if err := vdlItem0.validate(vdlItemPath0); err != nil {
				return err
			}
		}
	}
	return nil
}

// transform converts preQuery to Query.
func (p *preQuery) transform() Query {
	var transTxId *string
	transTxId = p.TxId

	var transQuery string
	transQuery = *p.Query

	var transParams *[]QueryParam
	if p.Params != nil {
		var valueParams []QueryParam
		valueParams = make([]QueryParam, len(*p.Params))
		for vdlIndex0, vdlItem0 := range *p.Params {
			var vdlTransformed0 QueryParam
			vdlTransformed0 = QueryParam(vdlItem0.transform())
			valueParams[vdlIndex0] = vdlTransformed0
		}
		transParams = &valueParams
	}

	return Query{
		TxId:   transTxId,
		Query:  transQuery,
		Params: transParams,
	}
}

// UnmarshalJSON decodes Query while requiring every non-optional JSON field.
func (x *Query) UnmarshalJSON(data []byte) error {
	var pre preQuery
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetTxId returns the TxId field. It returns the zero value when the receiver or field is nil.
func (x *Query) GetTxId() string {
	if x != nil && x.TxId != nil {
		return *x.TxId
	}
	var zero string
	return zero
}

// GetTxIdOr returns the TxId field. It returns defaultValue when the receiver or field is nil.
func (x *Query) GetTxIdOr(defaultValue string) string {
	if x != nil && x.TxId != nil {
		return *x.TxId
	}
	return defaultValue
}

// GetQuery returns the Query field. It returns the zero value when the receiver is nil.
func (x *Query) GetQuery() string {
	if x != nil {
		return x.Query
	}
	var zero string
	return zero
}

// GetQueryOr returns the Query field. It returns defaultValue when the receiver is nil.
func (x *Query) GetQueryOr(defaultValue string) string {
	if x != nil {
		return x.Query
	}
	return defaultValue
}

// GetParams returns the Params field. It returns the zero value when the receiver or field is nil.
func (x *Query) GetParams() []QueryParam {
	if x != nil && x.Params != nil {
		return *x.Params
	}
	var zero []QueryParam
	return zero
}

// GetParamsOr returns the Params field. It returns defaultValue when the receiver or field is nil.
func (x *Query) GetParamsOr(defaultValue []QueryParam) []QueryParam {
	if x != nil && x.Params != nil {
		return *x.Params
	}
	return defaultValue
}

// QueryParam represents a VDL object.
type QueryParam struct {
	// Parameter name for named parameters. Omitted for positional parameters.
	Name *string `json:"name,omitempty"`
	// The parameter value.
	Value SqliteValue `json:"value"`
}

// preQueryParam mirrors QueryParam during strict JSON decoding.
type preQueryParam struct {
	Name  *string      `json:"name,omitempty"`
	Value *SqliteValue `json:"value"`
}

// validate reports whether preQueryParam satisfies strict JSON requirements.
func (p *preQueryParam) validate(parentPath string) error {
	vdlPathValue := "value"
	if parentPath != "" {
		vdlPathValue = parentPath + ".value"
	}
	if p.Value == nil {
		return fmt.Errorf("field %s is required", vdlPathValue)
	}
	return nil
}

// transform converts preQueryParam to QueryParam.
func (p *preQueryParam) transform() QueryParam {
	var transName *string
	transName = p.Name

	var transValue SqliteValue
	transValue = *p.Value

	return QueryParam{
		Name:  transName,
		Value: transValue,
	}
}

// UnmarshalJSON decodes QueryParam while requiring every non-optional JSON field.
func (x *QueryParam) UnmarshalJSON(data []byte) error {
	var pre preQueryParam
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetName returns the Name field. It returns the zero value when the receiver or field is nil.
func (x *QueryParam) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	var zero string
	return zero
}

// GetNameOr returns the Name field. It returns defaultValue when the receiver or field is nil.
func (x *QueryParam) GetNameOr(defaultValue string) string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return defaultValue
}

// GetValue returns the Value field. It returns the zero value when the receiver is nil.
func (x *QueryParam) GetValue() SqliteValue {
	if x != nil {
		return x.Value
	}
	var zero SqliteValue
	return zero
}

// GetValueOr returns the Value field. It returns defaultValue when the receiver is nil.
func (x *QueryParam) GetValueOr(defaultValue SqliteValue) SqliteValue {
	if x != nil {
		return x.Value
	}
	return defaultValue
}

// QueryResult represents a VDL object.
type QueryResult struct {
	// The type of result (read, write, begin, commit, rollback, or error).
	Type QueryResultType `json:"type"`
	// Query execution time in seconds (as a floating-point duration).
	Time float64 `json:"time"`
	// Error message, present when type is "error".
	Error *string `json:"error,omitempty"`
	// Transaction ID, present when type is "begin".
	TxId *string `json:"txId,omitempty"`
	// The rowid of the last inserted row, present for write results.
	LastInsertId *int64 `json:"lastInsertId,omitempty"`
	// The number of rows affected, present for write results.
	RowsAffected *int64 `json:"rowsAffected,omitempty"`
	// Column names for the returned rows, present for read/write results.
	Columns *[]string `json:"columns,omitempty"`
	// Storage class of each column for the returned rows.
	Types *[]SqliteStorageClass `json:"types,omitempty"`
	// The returned rows, each row being an array of SqliteValue.
	Rows *[][]SqliteValue `json:"rows,omitempty"`
}

// preQueryResult mirrors QueryResult during strict JSON decoding.
type preQueryResult struct {
	Type         *QueryResultType      `json:"type"`
	Time         *float64              `json:"time"`
	Error        *string               `json:"error,omitempty"`
	TxId         *string               `json:"txId,omitempty"`
	LastInsertId *int64                `json:"lastInsertId,omitempty"`
	RowsAffected *int64                `json:"rowsAffected,omitempty"`
	Columns      *[]string             `json:"columns,omitempty"`
	Types        *[]SqliteStorageClass `json:"types,omitempty"`
	Rows         *[][]SqliteValue      `json:"rows,omitempty"`
}

// validate reports whether preQueryResult satisfies strict JSON requirements.
func (p *preQueryResult) validate(parentPath string) error {
	vdlPathType := "type"
	if parentPath != "" {
		vdlPathType = parentPath + ".type"
	}
	if p.Type == nil {
		return fmt.Errorf("field %s is required", vdlPathType)
	}

	vdlPathTime := "time"
	if parentPath != "" {
		vdlPathTime = parentPath + ".time"
	}
	if p.Time == nil {
		return fmt.Errorf("field %s is required", vdlPathTime)
	}

	return nil
}

// transform converts preQueryResult to QueryResult.
func (p *preQueryResult) transform() QueryResult {
	var transType QueryResultType
	transType = *p.Type

	var transTime float64
	transTime = *p.Time

	var transError *string
	transError = p.Error

	var transTxId *string
	transTxId = p.TxId

	var transLastInsertId *int64
	transLastInsertId = p.LastInsertId

	var transRowsAffected *int64
	transRowsAffected = p.RowsAffected

	var transColumns *[]string
	transColumns = p.Columns

	var transTypes *[]SqliteStorageClass
	transTypes = p.Types

	var transRows *[][]SqliteValue
	transRows = p.Rows

	return QueryResult{
		Type:         transType,
		Time:         transTime,
		Error:        transError,
		TxId:         transTxId,
		LastInsertId: transLastInsertId,
		RowsAffected: transRowsAffected,
		Columns:      transColumns,
		Types:        transTypes,
		Rows:         transRows,
	}
}

// UnmarshalJSON decodes QueryResult while requiring every non-optional JSON field.
func (x *QueryResult) UnmarshalJSON(data []byte) error {
	var pre preQueryResult
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetType returns the Type field. It returns the zero value when the receiver is nil.
func (x *QueryResult) GetType() QueryResultType {
	if x != nil {
		return x.Type
	}
	var zero QueryResultType
	return zero
}

// GetTypeOr returns the Type field. It returns defaultValue when the receiver is nil.
func (x *QueryResult) GetTypeOr(defaultValue QueryResultType) QueryResultType {
	if x != nil {
		return x.Type
	}
	return defaultValue
}

// GetTime returns the Time field. It returns the zero value when the receiver is nil.
func (x *QueryResult) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	var zero float64
	return zero
}

// GetTimeOr returns the Time field. It returns defaultValue when the receiver is nil.
func (x *QueryResult) GetTimeOr(defaultValue float64) float64 {
	if x != nil {
		return x.Time
	}
	return defaultValue
}

// GetError returns the Error field. It returns the zero value when the receiver or field is nil.
func (x *QueryResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	var zero string
	return zero
}

// GetErrorOr returns the Error field. It returns defaultValue when the receiver or field is nil.
func (x *QueryResult) GetErrorOr(defaultValue string) string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return defaultValue
}

// GetTxId returns the TxId field. It returns the zero value when the receiver or field is nil.
func (x *QueryResult) GetTxId() string {
	if x != nil && x.TxId != nil {
		return *x.TxId
	}
	var zero string
	return zero
}

// GetTxIdOr returns the TxId field. It returns defaultValue when the receiver or field is nil.
func (x *QueryResult) GetTxIdOr(defaultValue string) string {
	if x != nil && x.TxId != nil {
		return *x.TxId
	}
	return defaultValue
}

// GetLastInsertId returns the LastInsertId field. It returns the zero value when the receiver or field is nil.
func (x *QueryResult) GetLastInsertId() int64 {
	if x != nil && x.LastInsertId != nil {
		return *x.LastInsertId
	}
	var zero int64
	return zero
}

// GetLastInsertIdOr returns the LastInsertId field. It returns defaultValue when the receiver or field is nil.
func (x *QueryResult) GetLastInsertIdOr(defaultValue int64) int64 {
	if x != nil && x.LastInsertId != nil {
		return *x.LastInsertId
	}
	return defaultValue
}

// GetRowsAffected returns the RowsAffected field. It returns the zero value when the receiver or field is nil.
func (x *QueryResult) GetRowsAffected() int64 {
	if x != nil && x.RowsAffected != nil {
		return *x.RowsAffected
	}
	var zero int64
	return zero
}

// GetRowsAffectedOr returns the RowsAffected field. It returns defaultValue when the receiver or field is nil.
func (x *QueryResult) GetRowsAffectedOr(defaultValue int64) int64 {
	if x != nil && x.RowsAffected != nil {
		return *x.RowsAffected
	}
	return defaultValue
}

// GetColumns returns the Columns field. It returns the zero value when the receiver or field is nil.
func (x *QueryResult) GetColumns() []string {
	if x != nil && x.Columns != nil {
		return *x.Columns
	}
	var zero []string
	return zero
}

// GetColumnsOr returns the Columns field. It returns defaultValue when the receiver or field is nil.
func (x *QueryResult) GetColumnsOr(defaultValue []string) []string {
	if x != nil && x.Columns != nil {
		return *x.Columns
	}
	return defaultValue
}

// GetTypes returns the Types field. It returns the zero value when the receiver or field is nil.
func (x *QueryResult) GetTypes() []SqliteStorageClass {
	if x != nil && x.Types != nil {
		return *x.Types
	}
	var zero []SqliteStorageClass
	return zero
}

// GetTypesOr returns the Types field. It returns defaultValue when the receiver or field is nil.
func (x *QueryResult) GetTypesOr(defaultValue []SqliteStorageClass) []SqliteStorageClass {
	if x != nil && x.Types != nil {
		return *x.Types
	}
	return defaultValue
}

// GetRows returns the Rows field. It returns the zero value when the receiver or field is nil.
func (x *QueryResult) GetRows() [][]SqliteValue {
	if x != nil && x.Rows != nil {
		return *x.Rows
	}
	var zero [][]SqliteValue
	return zero
}

// GetRowsOr returns the Rows field. It returns defaultValue when the receiver or field is nil.
func (x *QueryResult) GetRowsOr(defaultValue [][]SqliteValue) [][]SqliteValue {
	if x != nil && x.Rows != nil {
		return *x.Rows
	}
	return defaultValue
}

// SqliteValue represents a VDL object.
type SqliteValue struct {
	// SQL NULL value.
	Null *bool `json:"null,omitempty"`
	// SQL INTEGER value.
	Integer *int64 `json:"integer,omitempty"`
	// SQL REAL value.
	Real *float64 `json:"real,omitempty"`
	// SQL TEXT value.
	Text *string `json:"text,omitempty"`
	// SQL BLOB value encoded as base64.
	Blob *string `json:"blob,omitempty"`
}

// GetNull returns the Null field. It returns the zero value when the receiver or field is nil.
func (x *SqliteValue) GetNull() bool {
	if x != nil && x.Null != nil {
		return *x.Null
	}
	var zero bool
	return zero
}

// GetNullOr returns the Null field. It returns defaultValue when the receiver or field is nil.
func (x *SqliteValue) GetNullOr(defaultValue bool) bool {
	if x != nil && x.Null != nil {
		return *x.Null
	}
	return defaultValue
}

// GetInteger returns the Integer field. It returns the zero value when the receiver or field is nil.
func (x *SqliteValue) GetInteger() int64 {
	if x != nil && x.Integer != nil {
		return *x.Integer
	}
	var zero int64
	return zero
}

// GetIntegerOr returns the Integer field. It returns defaultValue when the receiver or field is nil.
func (x *SqliteValue) GetIntegerOr(defaultValue int64) int64 {
	if x != nil && x.Integer != nil {
		return *x.Integer
	}
	return defaultValue
}

// GetReal returns the Real field. It returns the zero value when the receiver or field is nil.
func (x *SqliteValue) GetReal() float64 {
	if x != nil && x.Real != nil {
		return *x.Real
	}
	var zero float64
	return zero
}

// GetRealOr returns the Real field. It returns defaultValue when the receiver or field is nil.
func (x *SqliteValue) GetRealOr(defaultValue float64) float64 {
	if x != nil && x.Real != nil {
		return *x.Real
	}
	return defaultValue
}

// GetText returns the Text field. It returns the zero value when the receiver or field is nil.
func (x *SqliteValue) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	var zero string
	return zero
}

// GetTextOr returns the Text field. It returns defaultValue when the receiver or field is nil.
func (x *SqliteValue) GetTextOr(defaultValue string) string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return defaultValue
}

// GetBlob returns the Blob field. It returns the zero value when the receiver or field is nil.
func (x *SqliteValue) GetBlob() string {
	if x != nil && x.Blob != nil {
		return *x.Blob
	}
	var zero string
	return zero
}

// GetBlobOr returns the Blob field. It returns defaultValue when the receiver or field is nil.
func (x *SqliteValue) GetBlobOr(defaultValue string) string {
	if x != nil && x.Blob != nil {
		return *x.Blob
	}
	return defaultValue
}

// Stats represents a VDL object.
type Stats struct {
	// The server start time.
	StartedAt time.Time `json:"startedAt"`
	// Number of seconds since the server started.
	UptimeSeconds float64 `json:"uptimeSeconds"`
	// Cumulative counters for all completed operations.
	Totals StatsTotalsCounters `json:"totals"`
	// Counters for currently queued or in-flight operations.
	Queued StatsQueuedCounters `json:"queued"`
	// Per-minute counters keyed by UTC minute in RFC3339 format.
	Minutes map[string]StatsTotalsCounters `json:"minutes"`
}

// preStats mirrors Stats during strict JSON decoding.
type preStats struct {
	StartedAt     *time.Time                         `json:"startedAt"`
	UptimeSeconds *float64                           `json:"uptimeSeconds"`
	Totals        *preStatsTotalsCounters            `json:"totals"`
	Queued        *preStatsQueuedCounters            `json:"queued"`
	Minutes       *map[string]preStatsTotalsCounters `json:"minutes"`
}

// validate reports whether preStats satisfies strict JSON requirements.
func (p *preStats) validate(parentPath string) error {
	vdlPathStartedAt := "startedAt"
	if parentPath != "" {
		vdlPathStartedAt = parentPath + ".startedAt"
	}
	if p.StartedAt == nil {
		return fmt.Errorf("field %s is required", vdlPathStartedAt)
	}

	vdlPathUptimeSeconds := "uptimeSeconds"
	if parentPath != "" {
		vdlPathUptimeSeconds = parentPath + ".uptimeSeconds"
	}
	if p.UptimeSeconds == nil {
		return fmt.Errorf("field %s is required", vdlPathUptimeSeconds)
	}

	vdlPathTotals := "totals"
	if parentPath != "" {
		vdlPathTotals = parentPath + ".totals"
	}
	if p.Totals == nil {
		return fmt.Errorf("field %s is required", vdlPathTotals)
	}
	if p.Totals != nil {
		if err := p.Totals.validate(vdlPathTotals); err != nil {
			return err
		}
	}

	vdlPathQueued := "queued"
	if parentPath != "" {
		vdlPathQueued = parentPath + ".queued"
	}
	if p.Queued == nil {
		return fmt.Errorf("field %s is required", vdlPathQueued)
	}
	if p.Queued != nil {
		if err := p.Queued.validate(vdlPathQueued); err != nil {
			return err
		}
	}

	vdlPathMinutes := "minutes"
	if parentPath != "" {
		vdlPathMinutes = parentPath + ".minutes"
	}
	if p.Minutes == nil {
		return fmt.Errorf("field %s is required", vdlPathMinutes)
	}
	if p.Minutes != nil {
		for vdlKey0, vdlValue0 := range *p.Minutes {
			vdlValuePath0 := fmt.Sprintf("%s[%q]", vdlPathMinutes, vdlKey0)
			if err := vdlValue0.validate(vdlValuePath0); err != nil {
				return err
			}
		}
	}
	return nil
}

// transform converts preStats to Stats.
func (p *preStats) transform() Stats {
	var transStartedAt time.Time
	transStartedAt = *p.StartedAt

	var transUptimeSeconds float64
	transUptimeSeconds = *p.UptimeSeconds

	var transTotals StatsTotalsCounters
	transTotals = StatsTotalsCounters(p.Totals.transform())

	var transQueued StatsQueuedCounters
	transQueued = StatsQueuedCounters(p.Queued.transform())

	var transMinutes map[string]StatsTotalsCounters
	transMinutes = make(map[string]StatsTotalsCounters, len(*p.Minutes))
	for vdlKey0, vdlValue0 := range *p.Minutes {
		var vdlTransformed0 StatsTotalsCounters
		vdlTransformed0 = StatsTotalsCounters(vdlValue0.transform())
		transMinutes[vdlKey0] = vdlTransformed0
	}

	return Stats{
		StartedAt:     transStartedAt,
		UptimeSeconds: transUptimeSeconds,
		Totals:        transTotals,
		Queued:        transQueued,
		Minutes:       transMinutes,
	}
}

// UnmarshalJSON decodes Stats while requiring every non-optional JSON field.
func (x *Stats) UnmarshalJSON(data []byte) error {
	var pre preStats
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetStartedAt returns the StartedAt field. It returns the zero value when the receiver is nil.
func (x *Stats) GetStartedAt() time.Time {
	if x != nil {
		return x.StartedAt
	}
	var zero time.Time
	return zero
}

// GetStartedAtOr returns the StartedAt field. It returns defaultValue when the receiver is nil.
func (x *Stats) GetStartedAtOr(defaultValue time.Time) time.Time {
	if x != nil {
		return x.StartedAt
	}
	return defaultValue
}

// GetUptimeSeconds returns the UptimeSeconds field. It returns the zero value when the receiver is nil.
func (x *Stats) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	var zero float64
	return zero
}

// GetUptimeSecondsOr returns the UptimeSeconds field. It returns defaultValue when the receiver is nil.
func (x *Stats) GetUptimeSecondsOr(defaultValue float64) float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return defaultValue
}

// GetTotals returns the Totals field. It returns the zero value when the receiver is nil.
func (x *Stats) GetTotals() StatsTotalsCounters {
	if x != nil {
		return x.Totals
	}
	var zero StatsTotalsCounters
	return zero
}

// GetTotalsOr returns the Totals field. It returns defaultValue when the receiver is nil.
func (x *Stats) GetTotalsOr(defaultValue StatsTotalsCounters) StatsTotalsCounters {
	if x != nil {
		return x.Totals
	}
	return defaultValue
}

// GetQueued returns the Queued field. It returns the zero value when the receiver is nil.
func (x *Stats) GetQueued() StatsQueuedCounters {
	if x != nil {
		return x.Queued
	}
	var zero StatsQueuedCounters
	return zero
}

// GetQueuedOr returns the Queued field. It returns defaultValue when the receiver is nil.
func (x *Stats) GetQueuedOr(defaultValue StatsQueuedCounters) StatsQueuedCounters {
	if x != nil {
		return x.Queued
	}
	return defaultValue
}

// GetMinutes returns the Minutes field. It returns the zero value when the receiver is nil.
func (x *Stats) GetMinutes() map[string]StatsTotalsCounters {
	if x != nil {
		return x.Minutes
	}
	var zero map[string]StatsTotalsCounters
	return zero
}

// GetMinutesOr returns the Minutes field. It returns defaultValue when the receiver is nil.
func (x *Stats) GetMinutesOr(defaultValue map[string]StatsTotalsCounters) map[string]StatsTotalsCounters {
	if x != nil {
		return x.Minutes
	}
	return defaultValue
}

// StatsQueuedCounters represents a VDL object.
type StatsQueuedCounters struct {
	// Number of BEGIN TRANSACTION statements currently queued.
	Begins int64 `json:"begins"`
	// Number of write queries currently queued.
	Writes int64 `json:"writes"`
	// Number of HTTP requests currently being processed or queued.
	HttpRequests int64 `json:"httpRequests"`
}

// preStatsQueuedCounters mirrors StatsQueuedCounters during strict JSON decoding.
type preStatsQueuedCounters struct {
	Begins       *int64 `json:"begins"`
	Writes       *int64 `json:"writes"`
	HttpRequests *int64 `json:"httpRequests"`
}

// validate reports whether preStatsQueuedCounters satisfies strict JSON requirements.
func (p *preStatsQueuedCounters) validate(parentPath string) error {
	vdlPathBegins := "begins"
	if parentPath != "" {
		vdlPathBegins = parentPath + ".begins"
	}
	if p.Begins == nil {
		return fmt.Errorf("field %s is required", vdlPathBegins)
	}

	vdlPathWrites := "writes"
	if parentPath != "" {
		vdlPathWrites = parentPath + ".writes"
	}
	if p.Writes == nil {
		return fmt.Errorf("field %s is required", vdlPathWrites)
	}

	vdlPathHttpRequests := "httpRequests"
	if parentPath != "" {
		vdlPathHttpRequests = parentPath + ".httpRequests"
	}
	if p.HttpRequests == nil {
		return fmt.Errorf("field %s is required", vdlPathHttpRequests)
	}
	return nil
}

// transform converts preStatsQueuedCounters to StatsQueuedCounters.
func (p *preStatsQueuedCounters) transform() StatsQueuedCounters {
	var transBegins int64
	transBegins = *p.Begins

	var transWrites int64
	transWrites = *p.Writes

	var transHttpRequests int64
	transHttpRequests = *p.HttpRequests

	return StatsQueuedCounters{
		Begins:       transBegins,
		Writes:       transWrites,
		HttpRequests: transHttpRequests,
	}
}

// UnmarshalJSON decodes StatsQueuedCounters while requiring every non-optional JSON field.
func (x *StatsQueuedCounters) UnmarshalJSON(data []byte) error {
	var pre preStatsQueuedCounters
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetBegins returns the Begins field. It returns the zero value when the receiver is nil.
func (x *StatsQueuedCounters) GetBegins() int64 {
	if x != nil {
		return x.Begins
	}
	var zero int64
	return zero
}

// GetBeginsOr returns the Begins field. It returns defaultValue when the receiver is nil.
func (x *StatsQueuedCounters) GetBeginsOr(defaultValue int64) int64 {
	if x != nil {
		return x.Begins
	}
	return defaultValue
}

// GetWrites returns the Writes field. It returns the zero value when the receiver is nil.
func (x *StatsQueuedCounters) GetWrites() int64 {
	if x != nil {
		return x.Writes
	}
	var zero int64
	return zero
}

// GetWritesOr returns the Writes field. It returns defaultValue when the receiver is nil.
func (x *StatsQueuedCounters) GetWritesOr(defaultValue int64) int64 {
	if x != nil {
		return x.Writes
	}
	return defaultValue
}

// GetHttpRequests returns the HttpRequests field. It returns the zero value when the receiver is nil.
func (x *StatsQueuedCounters) GetHttpRequests() int64 {
	if x != nil {
		return x.HttpRequests
	}
	var zero int64
	return zero
}

// GetHttpRequestsOr returns the HttpRequests field. It returns defaultValue when the receiver is nil.
func (x *StatsQueuedCounters) GetHttpRequestsOr(defaultValue int64) int64 {
	if x != nil {
		return x.HttpRequests
	}
	return defaultValue
}

// StatsTotalsCounters represents a VDL object.
type StatsTotalsCounters struct {
	// Total number of completed read queries.
	Reads int64 `json:"reads"`
	// Total number of completed write queries.
	Writes int64 `json:"writes"`
	// Total number of completed BEGIN TRANSACTION statements.
	Begins int64 `json:"begins"`
	// Total number of completed COMMIT statements.
	Commits int64 `json:"commits"`
	// Total number of completed ROLLBACK statements.
	Rollbacks int64 `json:"rollbacks"`
	// Total number of queries that resulted in an error.
	Errors int64 `json:"errors"`
	// Total number of HTTP requests received.
	HttpRequests int64 `json:"httpRequests"`
}

// preStatsTotalsCounters mirrors StatsTotalsCounters during strict JSON decoding.
type preStatsTotalsCounters struct {
	Reads        *int64 `json:"reads"`
	Writes       *int64 `json:"writes"`
	Begins       *int64 `json:"begins"`
	Commits      *int64 `json:"commits"`
	Rollbacks    *int64 `json:"rollbacks"`
	Errors       *int64 `json:"errors"`
	HttpRequests *int64 `json:"httpRequests"`
}

// validate reports whether preStatsTotalsCounters satisfies strict JSON requirements.
func (p *preStatsTotalsCounters) validate(parentPath string) error {
	vdlPathReads := "reads"
	if parentPath != "" {
		vdlPathReads = parentPath + ".reads"
	}
	if p.Reads == nil {
		return fmt.Errorf("field %s is required", vdlPathReads)
	}

	vdlPathWrites := "writes"
	if parentPath != "" {
		vdlPathWrites = parentPath + ".writes"
	}
	if p.Writes == nil {
		return fmt.Errorf("field %s is required", vdlPathWrites)
	}

	vdlPathBegins := "begins"
	if parentPath != "" {
		vdlPathBegins = parentPath + ".begins"
	}
	if p.Begins == nil {
		return fmt.Errorf("field %s is required", vdlPathBegins)
	}

	vdlPathCommits := "commits"
	if parentPath != "" {
		vdlPathCommits = parentPath + ".commits"
	}
	if p.Commits == nil {
		return fmt.Errorf("field %s is required", vdlPathCommits)
	}

	vdlPathRollbacks := "rollbacks"
	if parentPath != "" {
		vdlPathRollbacks = parentPath + ".rollbacks"
	}
	if p.Rollbacks == nil {
		return fmt.Errorf("field %s is required", vdlPathRollbacks)
	}

	vdlPathErrors := "errors"
	if parentPath != "" {
		vdlPathErrors = parentPath + ".errors"
	}
	if p.Errors == nil {
		return fmt.Errorf("field %s is required", vdlPathErrors)
	}

	vdlPathHttpRequests := "httpRequests"
	if parentPath != "" {
		vdlPathHttpRequests = parentPath + ".httpRequests"
	}
	if p.HttpRequests == nil {
		return fmt.Errorf("field %s is required", vdlPathHttpRequests)
	}
	return nil
}

// transform converts preStatsTotalsCounters to StatsTotalsCounters.
func (p *preStatsTotalsCounters) transform() StatsTotalsCounters {
	var transReads int64
	transReads = *p.Reads

	var transWrites int64
	transWrites = *p.Writes

	var transBegins int64
	transBegins = *p.Begins

	var transCommits int64
	transCommits = *p.Commits

	var transRollbacks int64
	transRollbacks = *p.Rollbacks

	var transErrors int64
	transErrors = *p.Errors

	var transHttpRequests int64
	transHttpRequests = *p.HttpRequests

	return StatsTotalsCounters{
		Reads:        transReads,
		Writes:       transWrites,
		Begins:       transBegins,
		Commits:      transCommits,
		Rollbacks:    transRollbacks,
		Errors:       transErrors,
		HttpRequests: transHttpRequests,
	}
}

// UnmarshalJSON decodes StatsTotalsCounters while requiring every non-optional JSON field.
func (x *StatsTotalsCounters) UnmarshalJSON(data []byte) error {
	var pre preStatsTotalsCounters
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetReads returns the Reads field. It returns the zero value when the receiver is nil.
func (x *StatsTotalsCounters) GetReads() int64 {
	if x != nil {
		return x.Reads
	}
	var zero int64
	return zero
}

// GetReadsOr returns the Reads field. It returns defaultValue when the receiver is nil.
func (x *StatsTotalsCounters) GetReadsOr(defaultValue int64) int64 {
	if x != nil {
		return x.Reads
	}
	return defaultValue
}

// GetWrites returns the Writes field. It returns the zero value when the receiver is nil.
func (x *StatsTotalsCounters) GetWrites() int64 {
	if x != nil {
		return x.Writes
	}
	var zero int64
	return zero
}

// GetWritesOr returns the Writes field. It returns defaultValue when the receiver is nil.
func (x *StatsTotalsCounters) GetWritesOr(defaultValue int64) int64 {
	if x != nil {
		return x.Writes
	}
	return defaultValue
}

// GetBegins returns the Begins field. It returns the zero value when the receiver is nil.
func (x *StatsTotalsCounters) GetBegins() int64 {
	if x != nil {
		return x.Begins
	}
	var zero int64
	return zero
}

// GetBeginsOr returns the Begins field. It returns defaultValue when the receiver is nil.
func (x *StatsTotalsCounters) GetBeginsOr(defaultValue int64) int64 {
	if x != nil {
		return x.Begins
	}
	return defaultValue
}

// GetCommits returns the Commits field. It returns the zero value when the receiver is nil.
func (x *StatsTotalsCounters) GetCommits() int64 {
	if x != nil {
		return x.Commits
	}
	var zero int64
	return zero
}

// GetCommitsOr returns the Commits field. It returns defaultValue when the receiver is nil.
func (x *StatsTotalsCounters) GetCommitsOr(defaultValue int64) int64 {
	if x != nil {
		return x.Commits
	}
	return defaultValue
}

// GetRollbacks returns the Rollbacks field. It returns the zero value when the receiver is nil.
func (x *StatsTotalsCounters) GetRollbacks() int64 {
	if x != nil {
		return x.Rollbacks
	}
	var zero int64
	return zero
}

// GetRollbacksOr returns the Rollbacks field. It returns defaultValue when the receiver is nil.
func (x *StatsTotalsCounters) GetRollbacksOr(defaultValue int64) int64 {
	if x != nil {
		return x.Rollbacks
	}
	return defaultValue
}

// GetErrors returns the Errors field. It returns the zero value when the receiver is nil.
func (x *StatsTotalsCounters) GetErrors() int64 {
	if x != nil {
		return x.Errors
	}
	var zero int64
	return zero
}

// GetErrorsOr returns the Errors field. It returns defaultValue when the receiver is nil.
func (x *StatsTotalsCounters) GetErrorsOr(defaultValue int64) int64 {
	if x != nil {
		return x.Errors
	}
	return defaultValue
}

// GetHttpRequests returns the HttpRequests field. It returns the zero value when the receiver is nil.
func (x *StatsTotalsCounters) GetHttpRequests() int64 {
	if x != nil {
		return x.HttpRequests
	}
	var zero int64
	return zero
}

// GetHttpRequestsOr returns the HttpRequests field. It returns defaultValue when the receiver is nil.
func (x *StatsTotalsCounters) GetHttpRequestsOr(defaultValue int64) int64 {
	if x != nil {
		return x.HttpRequests
	}
	return defaultValue
}

// System represents a VDL object.
type System struct {
	// Checks whether the server can perform a basic database read.
	Health SystemHealth `json:"health"`
	// Returns the authentication role for the current session.
	Session SystemSession `json:"session"`
	// Returns server information and runtime statistics.
	Status SystemStatus `json:"status"`
}

// preSystem mirrors System during strict JSON decoding.
type preSystem struct {
	Health  *preSystemHealth  `json:"health"`
	Session *preSystemSession `json:"session"`
	Status  *preSystemStatus  `json:"status"`
}

// validate reports whether preSystem satisfies strict JSON requirements.
func (p *preSystem) validate(parentPath string) error {
	vdlPathHealth := "health"
	if parentPath != "" {
		vdlPathHealth = parentPath + ".health"
	}
	if p.Health == nil {
		return fmt.Errorf("field %s is required", vdlPathHealth)
	}
	if p.Health != nil {
		if err := p.Health.validate(vdlPathHealth); err != nil {
			return err
		}
	}

	vdlPathSession := "session"
	if parentPath != "" {
		vdlPathSession = parentPath + ".session"
	}
	if p.Session == nil {
		return fmt.Errorf("field %s is required", vdlPathSession)
	}
	if p.Session != nil {
		if err := p.Session.validate(vdlPathSession); err != nil {
			return err
		}
	}

	vdlPathStatus := "status"
	if parentPath != "" {
		vdlPathStatus = parentPath + ".status"
	}
	if p.Status == nil {
		return fmt.Errorf("field %s is required", vdlPathStatus)
	}
	if p.Status != nil {
		if err := p.Status.validate(vdlPathStatus); err != nil {
			return err
		}
	}
	return nil
}

// transform converts preSystem to System.
func (p *preSystem) transform() System {
	var transHealth SystemHealth
	transHealth = SystemHealth(p.Health.transform())

	var transSession SystemSession
	transSession = SystemSession(p.Session.transform())

	var transStatus SystemStatus
	transStatus = SystemStatus(p.Status.transform())

	return System{
		Health:  transHealth,
		Session: transSession,
		Status:  transStatus,
	}
}

// UnmarshalJSON decodes System while requiring every non-optional JSON field.
func (x *System) UnmarshalJSON(data []byte) error {
	var pre preSystem
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetHealth returns the Health field. It returns the zero value when the receiver is nil.
func (x *System) GetHealth() SystemHealth {
	if x != nil {
		return x.Health
	}
	var zero SystemHealth
	return zero
}

// GetHealthOr returns the Health field. It returns defaultValue when the receiver is nil.
func (x *System) GetHealthOr(defaultValue SystemHealth) SystemHealth {
	if x != nil {
		return x.Health
	}
	return defaultValue
}

// GetSession returns the Session field. It returns the zero value when the receiver is nil.
func (x *System) GetSession() SystemSession {
	if x != nil {
		return x.Session
	}
	var zero SystemSession
	return zero
}

// GetSessionOr returns the Session field. It returns defaultValue when the receiver is nil.
func (x *System) GetSessionOr(defaultValue SystemSession) SystemSession {
	if x != nil {
		return x.Session
	}
	return defaultValue
}

// GetStatus returns the Status field. It returns the zero value when the receiver is nil.
func (x *System) GetStatus() SystemStatus {
	if x != nil {
		return x.Status
	}
	var zero SystemStatus
	return zero
}

// GetStatusOr returns the Status field. It returns defaultValue when the receiver is nil.
func (x *System) GetStatusOr(defaultValue SystemStatus) SystemStatus {
	if x != nil {
		return x.Status
	}
	return defaultValue
}

// SystemHealth represents the inline object declared at System.health.
type SystemHealth struct {
	Output SystemHealthOutput `json:"output"`
}

// preSystemHealth mirrors SystemHealth during strict JSON decoding.
type preSystemHealth struct {
	Output *preSystemHealthOutput `json:"output"`
}

// validate reports whether preSystemHealth satisfies strict JSON requirements.
func (p *preSystemHealth) validate(parentPath string) error {
	vdlPathOutput := "output"
	if parentPath != "" {
		vdlPathOutput = parentPath + ".output"
	}
	if p.Output == nil {
		return fmt.Errorf("field %s is required", vdlPathOutput)
	}
	if p.Output != nil {
		if err := p.Output.validate(vdlPathOutput); err != nil {
			return err
		}
	}
	return nil
}

// transform converts preSystemHealth to SystemHealth.
func (p *preSystemHealth) transform() SystemHealth {
	var transOutput SystemHealthOutput
	transOutput = SystemHealthOutput(p.Output.transform())

	return SystemHealth{
		Output: transOutput,
	}
}

// UnmarshalJSON decodes SystemHealth while requiring every non-optional JSON field.
func (x *SystemHealth) UnmarshalJSON(data []byte) error {
	var pre preSystemHealth
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetOutput returns the Output field. It returns the zero value when the receiver is nil.
func (x *SystemHealth) GetOutput() SystemHealthOutput {
	if x != nil {
		return x.Output
	}
	var zero SystemHealthOutput
	return zero
}

// GetOutputOr returns the Output field. It returns defaultValue when the receiver is nil.
func (x *SystemHealth) GetOutputOr(defaultValue SystemHealthOutput) SystemHealthOutput {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// SystemHealthOutput represents the inline object declared at System.health.output.
type SystemHealthOutput struct {
	// Whether the server is healthy and fully operational.
	Healthy bool `json:"healthy"`
	// Whether the database is reachable and responsive.
	Database bool `json:"database"`
	// A human-readable message describing the health state.
	Message string `json:"message"`
}

// preSystemHealthOutput mirrors SystemHealthOutput during strict JSON decoding.
type preSystemHealthOutput struct {
	Healthy  *bool   `json:"healthy"`
	Database *bool   `json:"database"`
	Message  *string `json:"message"`
}

// validate reports whether preSystemHealthOutput satisfies strict JSON requirements.
func (p *preSystemHealthOutput) validate(parentPath string) error {
	vdlPathHealthy := "healthy"
	if parentPath != "" {
		vdlPathHealthy = parentPath + ".healthy"
	}
	if p.Healthy == nil {
		return fmt.Errorf("field %s is required", vdlPathHealthy)
	}

	vdlPathDatabase := "database"
	if parentPath != "" {
		vdlPathDatabase = parentPath + ".database"
	}
	if p.Database == nil {
		return fmt.Errorf("field %s is required", vdlPathDatabase)
	}

	vdlPathMessage := "message"
	if parentPath != "" {
		vdlPathMessage = parentPath + ".message"
	}
	if p.Message == nil {
		return fmt.Errorf("field %s is required", vdlPathMessage)
	}
	return nil
}

// transform converts preSystemHealthOutput to SystemHealthOutput.
func (p *preSystemHealthOutput) transform() SystemHealthOutput {
	var transHealthy bool
	transHealthy = *p.Healthy

	var transDatabase bool
	transDatabase = *p.Database

	var transMessage string
	transMessage = *p.Message

	return SystemHealthOutput{
		Healthy:  transHealthy,
		Database: transDatabase,
		Message:  transMessage,
	}
}

// UnmarshalJSON decodes SystemHealthOutput while requiring every non-optional JSON field.
func (x *SystemHealthOutput) UnmarshalJSON(data []byte) error {
	var pre preSystemHealthOutput
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetHealthy returns the Healthy field. It returns the zero value when the receiver is nil.
func (x *SystemHealthOutput) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	var zero bool
	return zero
}

// GetHealthyOr returns the Healthy field. It returns defaultValue when the receiver is nil.
func (x *SystemHealthOutput) GetHealthyOr(defaultValue bool) bool {
	if x != nil {
		return x.Healthy
	}
	return defaultValue
}

// GetDatabase returns the Database field. It returns the zero value when the receiver is nil.
func (x *SystemHealthOutput) GetDatabase() bool {
	if x != nil {
		return x.Database
	}
	var zero bool
	return zero
}

// GetDatabaseOr returns the Database field. It returns defaultValue when the receiver is nil.
func (x *SystemHealthOutput) GetDatabaseOr(defaultValue bool) bool {
	if x != nil {
		return x.Database
	}
	return defaultValue
}

// GetMessage returns the Message field. It returns the zero value when the receiver is nil.
func (x *SystemHealthOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	var zero string
	return zero
}

// GetMessageOr returns the Message field. It returns defaultValue when the receiver is nil.
func (x *SystemHealthOutput) GetMessageOr(defaultValue string) string {
	if x != nil {
		return x.Message
	}
	return defaultValue
}

// SystemSession represents the inline object declared at System.session.
type SystemSession struct {
	Output SystemSessionOutput `json:"output"`
}

// preSystemSession mirrors SystemSession during strict JSON decoding.
type preSystemSession struct {
	Output *preSystemSessionOutput `json:"output"`
}

// validate reports whether preSystemSession satisfies strict JSON requirements.
func (p *preSystemSession) validate(parentPath string) error {
	vdlPathOutput := "output"
	if parentPath != "" {
		vdlPathOutput = parentPath + ".output"
	}
	if p.Output == nil {
		return fmt.Errorf("field %s is required", vdlPathOutput)
	}
	if p.Output != nil {
		if err := p.Output.validate(vdlPathOutput); err != nil {
			return err
		}
	}
	return nil
}

// transform converts preSystemSession to SystemSession.
func (p *preSystemSession) transform() SystemSession {
	var transOutput SystemSessionOutput
	transOutput = SystemSessionOutput(p.Output.transform())

	return SystemSession{
		Output: transOutput,
	}
}

// UnmarshalJSON decodes SystemSession while requiring every non-optional JSON field.
func (x *SystemSession) UnmarshalJSON(data []byte) error {
	var pre preSystemSession
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetOutput returns the Output field. It returns the zero value when the receiver is nil.
func (x *SystemSession) GetOutput() SystemSessionOutput {
	if x != nil {
		return x.Output
	}
	var zero SystemSessionOutput
	return zero
}

// GetOutputOr returns the Output field. It returns defaultValue when the receiver is nil.
func (x *SystemSession) GetOutputOr(defaultValue SystemSessionOutput) SystemSessionOutput {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// SystemSessionOutput represents the inline object declared at System.session.output.
type SystemSessionOutput struct {
	// The authentication role assigned to the current session.
	Role AuthRole `json:"role"`
}

// preSystemSessionOutput mirrors SystemSessionOutput during strict JSON decoding.
type preSystemSessionOutput struct {
	Role *AuthRole `json:"role"`
}

// validate reports whether preSystemSessionOutput satisfies strict JSON requirements.
func (p *preSystemSessionOutput) validate(parentPath string) error {
	vdlPathRole := "role"
	if parentPath != "" {
		vdlPathRole = parentPath + ".role"
	}
	if p.Role == nil {
		return fmt.Errorf("field %s is required", vdlPathRole)
	}
	return nil
}

// transform converts preSystemSessionOutput to SystemSessionOutput.
func (p *preSystemSessionOutput) transform() SystemSessionOutput {
	var transRole AuthRole
	transRole = *p.Role

	return SystemSessionOutput{
		Role: transRole,
	}
}

// UnmarshalJSON decodes SystemSessionOutput while requiring every non-optional JSON field.
func (x *SystemSessionOutput) UnmarshalJSON(data []byte) error {
	var pre preSystemSessionOutput
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetRole returns the Role field. It returns the zero value when the receiver is nil.
func (x *SystemSessionOutput) GetRole() AuthRole {
	if x != nil {
		return x.Role
	}
	var zero AuthRole
	return zero
}

// GetRoleOr returns the Role field. It returns defaultValue when the receiver is nil.
func (x *SystemSessionOutput) GetRoleOr(defaultValue AuthRole) AuthRole {
	if x != nil {
		return x.Role
	}
	return defaultValue
}

// SystemStatus represents the inline object declared at System.status.
type SystemStatus struct {
	Output SystemStatusOutput `json:"output"`
}

// preSystemStatus mirrors SystemStatus during strict JSON decoding.
type preSystemStatus struct {
	Output *preSystemStatusOutput `json:"output"`
}

// validate reports whether preSystemStatus satisfies strict JSON requirements.
func (p *preSystemStatus) validate(parentPath string) error {
	vdlPathOutput := "output"
	if parentPath != "" {
		vdlPathOutput = parentPath + ".output"
	}
	if p.Output == nil {
		return fmt.Errorf("field %s is required", vdlPathOutput)
	}
	if p.Output != nil {
		if err := p.Output.validate(vdlPathOutput); err != nil {
			return err
		}
	}
	return nil
}

// transform converts preSystemStatus to SystemStatus.
func (p *preSystemStatus) transform() SystemStatus {
	var transOutput SystemStatusOutput
	transOutput = SystemStatusOutput(p.Output.transform())

	return SystemStatus{
		Output: transOutput,
	}
}

// UnmarshalJSON decodes SystemStatus while requiring every non-optional JSON field.
func (x *SystemStatus) UnmarshalJSON(data []byte) error {
	var pre preSystemStatus
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetOutput returns the Output field. It returns the zero value when the receiver is nil.
func (x *SystemStatus) GetOutput() SystemStatusOutput {
	if x != nil {
		return x.Output
	}
	var zero SystemStatusOutput
	return zero
}

// GetOutputOr returns the Output field. It returns defaultValue when the receiver is nil.
func (x *SystemStatus) GetOutputOr(defaultValue SystemStatusOutput) SystemStatusOutput {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// SystemStatusOutput represents the inline object declared at System.status.output.
type SystemStatusOutput struct {
	// The server name.
	Name string `json:"name"`
	// The server version string.
	Version string `json:"version"`
	// Current runtime statistics.
	Stats Stats `json:"stats"`
}

// preSystemStatusOutput mirrors SystemStatusOutput during strict JSON decoding.
type preSystemStatusOutput struct {
	Name    *string   `json:"name"`
	Version *string   `json:"version"`
	Stats   *preStats `json:"stats"`
}

// validate reports whether preSystemStatusOutput satisfies strict JSON requirements.
func (p *preSystemStatusOutput) validate(parentPath string) error {
	vdlPathName := "name"
	if parentPath != "" {
		vdlPathName = parentPath + ".name"
	}
	if p.Name == nil {
		return fmt.Errorf("field %s is required", vdlPathName)
	}

	vdlPathVersion := "version"
	if parentPath != "" {
		vdlPathVersion = parentPath + ".version"
	}
	if p.Version == nil {
		return fmt.Errorf("field %s is required", vdlPathVersion)
	}

	vdlPathStats := "stats"
	if parentPath != "" {
		vdlPathStats = parentPath + ".stats"
	}
	if p.Stats == nil {
		return fmt.Errorf("field %s is required", vdlPathStats)
	}
	if p.Stats != nil {
		if err := p.Stats.validate(vdlPathStats); err != nil {
			return err
		}
	}
	return nil
}

// transform converts preSystemStatusOutput to SystemStatusOutput.
func (p *preSystemStatusOutput) transform() SystemStatusOutput {
	var transName string
	transName = *p.Name

	var transVersion string
	transVersion = *p.Version

	var transStats Stats
	transStats = Stats(p.Stats.transform())

	return SystemStatusOutput{
		Name:    transName,
		Version: transVersion,
		Stats:   transStats,
	}
}

// UnmarshalJSON decodes SystemStatusOutput while requiring every non-optional JSON field.
func (x *SystemStatusOutput) UnmarshalJSON(data []byte) error {
	var pre preSystemStatusOutput
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetName returns the Name field. It returns the zero value when the receiver is nil.
func (x *SystemStatusOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	var zero string
	return zero
}

// GetNameOr returns the Name field. It returns defaultValue when the receiver is nil.
func (x *SystemStatusOutput) GetNameOr(defaultValue string) string {
	if x != nil {
		return x.Name
	}
	return defaultValue
}

// GetVersion returns the Version field. It returns the zero value when the receiver is nil.
func (x *SystemStatusOutput) GetVersion() string {
	if x != nil {
		return x.Version
	}
	var zero string
	return zero
}

// GetVersionOr returns the Version field. It returns defaultValue when the receiver is nil.
func (x *SystemStatusOutput) GetVersionOr(defaultValue string) string {
	if x != nil {
		return x.Version
	}
	return defaultValue
}

// GetStats returns the Stats field. It returns the zero value when the receiver is nil.
func (x *SystemStatusOutput) GetStats() Stats {
	if x != nil {
		return x.Stats
	}
	var zero Stats
	return zero
}

// GetStatsOr returns the Stats field. It returns defaultValue when the receiver is nil.
func (x *SystemStatusOutput) GetStatsOr(defaultValue Stats) Stats {
	if x != nil {
		return x.Stats
	}
	return defaultValue
}
